# Generated by Django 6.0.8 on 2026-10-06 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessCalendarYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scope", models.CharField(default="BR", max_length=16)),
                ("year", models.PositiveSmallIntegerField()),
                ("legal_basis", models.CharField(max_length=300)),
                ("source_url", models.URLField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("approved", "Aprovada"),
                            ("retired", "Retirada"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("scope", "year"),
            },
        ),
        migrations.CreateModel(
            name="NonBusinessDay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("day", models.DateField()),
                ("name", models.CharField(max_length=120)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="fiscal_calendar.businesscalendaryear",
                    ),
                ),
            ],
            options={
                "ordering": ("day",),
            },
        ),
        migrations.CreateModel(
            name="TaxDeadlineRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64)),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("title", models.CharField(max_length=120)),
                ("month_offset", models.PositiveSmallIntegerField(default=1)),
                (
                    "anchor",
                    models.CharField(
                        choices=[
                            ("day_of_month", "Dia do mês"),
                            ("last_day", "Último dia do mês"),
                            ("last_business_day", "Último dia útil do mês"),
                        ],
                        max_length=24,
                    ),
                ),
                ("day", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "non_business_shift",
                    models.CharField(
                        choices=[
                            ("previous", "Antecipa para o dia útil anterior"),
                            ("next", "Prorroga para o dia útil seguinte"),
                            ("none", "Não ajusta"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("valid_from", models.DateField(help_text="Primeira competência (dia 1) coberta.")),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Última competência coberta, quando houver.",
                        null=True,
                    ),
                ),
                ("legal_basis", models.CharField(max_length=300)),
                ("source_url", models.URLField(max_length=500)),
                ("source_checked_on", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("approved", "Aprovada"),
                            ("retired", "Retirada"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("code", "-version"),
            },
        ),
        migrations.AddConstraint(
            model_name="businesscalendaryear",
            constraint=models.UniqueConstraint(
                fields=("scope", "year"), name="fiscal_calendar_unique_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="businesscalendaryear",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "approved"), _negated=True),
                    models.Q(("approved_by__isnull", False), ("approved_at__isnull", False)),
                    _connector="OR",
                ),
                name="fiscal_calendar_year_approval_recorded",
            ),
        ),
        migrations.AddConstraint(
            model_name="nonbusinessday",
            constraint=models.UniqueConstraint(
                fields=("calendar", "day"), name="fiscal_calendar_unique_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="taxdeadlinerule",
            constraint=models.UniqueConstraint(
                fields=("code", "version"), name="fiscal_rule_unique_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="taxdeadlinerule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "approved"), _negated=True),
                    models.Q(("approved_by__isnull", False), ("approved_at__isnull", False)),
                    _connector="OR",
                ),
                name="fiscal_rule_approval_recorded",
            ),
        ),
        migrations.AddConstraint(
            model_name="taxdeadlinerule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("anchor", "day_of_month"), _negated=True),
                    models.Q(("day__gte", 1), ("day__lte", 31)),
                    _connector="OR",
                ),
                name="fiscal_rule_day_for_day_anchor",
            ),
        ),
    ]
