# Generated by Django 6.0.7 on 2026-09-09 17:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hub", "0001_initial"),
        ("organizations", "0002_alter_membership_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=160)),
                ("summary", apps.common.encryption.EncryptedTextField(blank=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "Usuário"), ("assistant", "Assistente")], max_length=12
                    ),
                ),
                ("content", apps.common.encryption.EncryptedTextField()),
                ("evidence", models.JSONField(default=list)),
                ("model_version", models.CharField(default="grounded-rules-v1", max_length=80)),
                ("context_hash", models.CharField(blank=True, max_length=64)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="intelligence.conversation",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="AnswerFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verdict",
                    models.CharField(
                        choices=[("helpful", "Resolveu"), ("not_helpful", "Não resolveu")],
                        max_length=16,
                    ),
                ),
                ("comment", apps.common.encryption.EncryptedTextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="intelligence.message",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("corpus_version", models.CharField(max_length=80)),
                ("adapter_version", models.CharField(blank=True, max_length=80)),
                ("metrics", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssistantSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("claude_fallback_enabled", models.BooleanField(default=False)),
                ("claude_full_data_allowed", models.BooleanField(default=False)),
                ("claude_allowed_roles", models.JSONField(default=list)),
                ("retention_days", models.PositiveSmallIntegerField(default=90)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization",), name="intelligence_settings_per_organization"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ClassificationDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("suggested_code", models.CharField(max_length=80)),
                ("rationale", apps.common.encryption.EncryptedTextField()),
                ("evidence", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente de revisão"),
                            ("approved", "Aprovado"),
                            ("rejected", "Rejeitado"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="hub.clientcompany"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drafts",
                        to="intelligence.conversation",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["organization", "created_at"], name="intelligenc_organiz_b1143b_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DataCatalogEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("module", models.CharField(max_length=64)),
                ("business_name", models.CharField(max_length=140)),
                ("description", models.TextField()),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[
                            ("operational", "Operacional"),
                            ("personal", "Pessoal"),
                            ("restricted", "Restrito"),
                            ("excluded", "Excluído"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_reference", models.CharField(max_length=240)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("module", "business_name"),
                "indexes": [
                    models.Index(
                        fields=["organization", "module", "enabled"],
                        name="intelligenc_organiz_42c140_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EgressAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=40)),
                ("purpose", models.CharField(max_length=80)),
                ("payload_hash", models.CharField(max_length=64)),
                ("role", models.CharField(max_length=16)),
                ("allowed", models.BooleanField(default=False)),
                ("model", models.CharField(blank=True, max_length=80)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["organization", "created_at"], name="intelligenc_organiz_a4f975_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IntelligenceConnector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("direct_odbc", "ODBC interno"),
                            ("edge_agent", "Agente de borda"),
                        ],
                        max_length=20,
                    ),
                ),
                ("status", models.CharField(default="not_configured", max_length=24)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("sync_lag_seconds", models.PositiveIntegerField(default=0)),
                ("device_fingerprint", models.CharField(blank=True, max_length=64)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "mode"), name="intelligence_connector_per_mode"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LearningCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_summary", apps.common.encryption.EncryptedTextField()),
                ("prior_answer", apps.common.encryption.EncryptedTextField()),
                ("candidate_answer", apps.common.encryption.EncryptedTextField()),
                ("evaluation", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Aguardando revisão"),
                            ("approved", "Aprovado"),
                            ("rejected", "Rejeitado"),
                            ("published", "Publicado"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "feedback",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate",
                        to="intelligence.answerfeedback",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["organization", "created_at"], name="intelligenc_organiz_cd414d_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["organization", "conversation", "created_at"],
                name="intelligenc_organiz_a4be0d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="answerfeedback",
            constraint=models.UniqueConstraint(
                fields=("message", "submitted_by"), name="intelligence_one_feedback_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="modelversion",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="intelligence_model_version_per_org"
            ),
        ),
    ]
