# Generated by Django 6.0.7 on 2026-09-09 17:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):
    dependencies = [
        ("intelligence", "0001_initial"),
        ("organizations", "0002_alter_membership_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("suite_name", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=100)),
                ("corpus_version", models.CharField(max_length=80)),
                ("total_cases", models.PositiveIntegerField(default=0)),
                ("correct_cases", models.PositiveIntegerField(default=0)),
                ("sourced_cases", models.PositiveIntegerField(default=0)),
                ("safety_regressions", models.PositiveIntegerField(default=0)),
                ("passed", models.BooleanField(default=False)),
                ("results", models.JSONField(default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["organization", "created_at"], name="intelligenc_organiz_0aa4b5_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Domínio"),
                            ("procedure", "Procedimento aprovado"),
                            ("dictionary", "Dicionário de dados"),
                            ("validated_case", "Caso histórico validado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("version", models.CharField(max_length=80)),
                ("source_reference", models.CharField(max_length=300)),
                ("content", apps.common.encryption.EncryptedTextField()),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Em curadoria"),
                            ("approved", "Aprovada"),
                            ("retired", "Retirada"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "content_hash"),
                        name="intelligence_unique_knowledge_content",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TrainingExample",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("risk", "Risco"),
                            ("classification", "Classificação"),
                            ("obligation", "Obrigação"),
                            ("safety", "Segurança"),
                        ],
                        max_length=20,
                    ),
                ),
                ("question", apps.common.encryption.EncryptedTextField()),
                ("expected_answer", apps.common.encryption.EncryptedTextField()),
                ("source_references", models.JSONField(default=list)),
                ("scenario_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Em curadoria"),
                            ("validated", "Validado"),
                            ("retired", "Retirado"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "scenario_hash"),
                        name="intelligence_unique_training_scenario",
                    )
                ],
            },
        ),
    ]
