# Generated by Django 6.0.8 on 2026-09-09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("intelligence", "0004_claudefallbackapproval")]

    operations = [
        migrations.CreateModel(
            name="SemanticPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("module", models.CharField(max_length=64)),
                ("tool_name", models.CharField(max_length=80)),
                ("query_name", models.CharField(blank=True, max_length=80)),
                ("source_reference", models.CharField(max_length=300)),
                ("data_classification", models.CharField(max_length=24)),
                ("company_key", models.CharField(max_length=120)),
                ("primary_key", models.CharField(max_length=120)),
                (
                    "update_strategy",
                    models.CharField(
                        choices=[
                            ("watermark", "Marca de atualização"),
                            ("snapshot_hash", "Snapshot com hash"),
                        ],
                        max_length=20,
                    ),
                ),
                ("max_rows", models.PositiveSmallIntegerField(default=100)),
                ("max_period_days", models.PositiveSmallIntegerField(default=366)),
                ("test_specification", models.JSONField(default=dict)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="semanticpackage",
            constraint=models.UniqueConstraint(
                fields=("organization", "tool_name", "query_name"),
                name="intelligence_unique_semantic_package",
            ),
        ),
        migrations.AddIndex(
            model_name="semanticpackage",
            index=models.Index(
                fields=["organization", "tool_name", "enabled"],
                name="intelligenc_organiz_faa9f6_idx",
            ),
        ),
    ]
