# Generated by Django 6.0.8 on 2026-09-09

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):
    dependencies = [("intelligence", "0005_semanticpackage")]

    operations = [
        migrations.CreateModel(
            name="ChatAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_name", models.CharField(max_length=180)),
                ("content_type", models.CharField(max_length=100)),
                ("byte_size", models.PositiveIntegerField()),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("encrypted_content_b64", apps.common.encryption.EncryptedTextField()),
                ("analysis", apps.common.encryption.EncryptedTextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Recebido"),
                            ("analyzed", "Analisado"),
                            ("awaiting_model", "Aguardando modelo local"),
                            ("rejected", "Recusado"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="intelligence.conversation",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to="intelligence.message",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="chatattachment",
            index=models.Index(
                fields=["organization", "conversation", "status"],
                name="intelligenc_organiz_137112_idx",
            ),
        ),
    ]
