# Generated by Django 6.0.7 on 2026-09-09

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):
    dependencies = [
        ("intelligence", "0006_chatattachment"),
        ("organizations", "0002_alter_membership_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ordinal", models.PositiveIntegerField()),
                ("content", apps.common.encryption.EncryptedTextField()),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="intelligence.knowledgesource",
                    ),
                ),
            ],
            options={
                "ordering": ("source_id", "ordinal"),
                "indexes": [
                    models.Index(
                        fields=["organization", "source", "ordinal"],
                        name="intelligenc_organiz_1ec055_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "content_hash"),
                        name="intelligence_unique_knowledge_chunk",
                    )
                ],
            },
        ),
    ]
