# Generated by Django 6.0.7 on 2026-09-09

from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):
    dependencies = [("intelligence", "0007_knowledgechunk")]

    operations = [
        migrations.AddField(
            model_name="assistantsettings",
            name="claude_api_key",
            field=apps.common.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name="egressaudit",
            name="estimated_cost_cents",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
