# Generated by Django 6.0.7 on 2026-09-09

import uuid

from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):
    dependencies = [("intelligence", "0008_assistantsettings_claude_api_key_and_more")]

    operations = [
        migrations.AddField(
            model_name="semanticpackage",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="semanticpackage",
            name="max_staleness_seconds",
            field=models.PositiveIntegerField(default=86400),
        ),
        migrations.CreateModel(
            name="MirrorRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_key", models.CharField(max_length=160)),
                ("payload", apps.common.encryption.EncryptedTextField()),
                ("payload_hash", models.CharField(db_index=True, max_length=64)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("synchronized_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "semantic_package",
                    models.ForeignKey(
                        on_delete=models.deletion.PROTECT,
                        related_name="records",
                        to="intelligence.semanticpackage",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="mirrorrecord",
            constraint=models.UniqueConstraint(
                fields=("semantic_package", "external_key"),
                name="intelligence_unique_mirror_record",
            ),
        ),
        migrations.AddIndex(
            model_name="mirrorrecord",
            index=models.Index(
                fields=["organization", "semantic_package", "company", "synchronized_at"],
                name="intelligence_mirror_scope_sync_idx",
            ),
        ),
    ]
