# Generated by Django 6.0.7 on 2026-09-09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("intelligence", "0009_mirrorrecord_semanticpackage_freshness")]

    operations = [
        migrations.RenameIndex(
            model_name="mirrorrecord",
            new_name="intelligenc_organiz_df8cac_idx",
            old_name="intelligence_mirror_scope_sync_idx",
        ),
    ]
