# Generated by Django 6.0.7 on 2026-09-09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "intelligence",
            "0010_rename_intelligence_mirror_scope_sync_idx_intelligenc_organiz_df8cac_idx",
        )
    ]

    operations = [
        migrations.CreateModel(
            name="DominioSchemaObject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("schema_name", models.CharField(blank=True, max_length=128)),
                ("object_name", models.CharField(max_length=128)),
                (
                    "object_kind",
                    models.CharField(
                        choices=[("table", "Tabela"), ("view", "Visão")], max_length=12
                    ),
                ),
                ("columns", models.JSONField(default=list)),
                ("structure_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[
                            ("operational", "Operacional"),
                            ("personal", "Pessoal"),
                            ("restricted", "Restrito"),
                            ("excluded", "Excluído"),
                        ],
                        default="restricted",
                        max_length=20,
                    ),
                ),
                ("approved_for_package", models.BooleanField(default=False)),
                ("last_discovered_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "approved_for_package", "sensitivity"],
                        name="intelligenc_organiz_d71690_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "schema_name", "object_name", "object_kind"),
                        name="intelligence_unique_dominio_schema_object",
                    )
                ],
            },
        ),
    ]
