# Generated by Django 6.0.7 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("intelligence", "0011_dominioschemaobject")]

    operations = [
        migrations.AddField(
            model_name="assistantsettings",
            name="claude_max_request_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="assistantsettings",
            name="claude_model",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
