# Generated by Django 6.0.7 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("intelligence", "0012_assistantsettings_claude_model_and_more")]

    operations = [
        migrations.AddField(
            model_name="assistantsettings",
            name="claude_curation_max_batch_requests",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="assistantsettings",
            name="claude_offline_curation_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
