# Generated by Django 6.0.7 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("intelligence", "0013_assistantsettings_claude_offline_curation")]

    operations = [
        migrations.AddField(
            model_name="edgeagent",
            name="mtls_certificate_sha256",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
