# Generated by Django 6.0.7 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("intelligence", "0014_edgeagent_mtls_certificate_sha256")]

    operations = [
        migrations.AddField(
            model_name="semanticpackage",
            name="schema_dependencies",
            field=models.JSONField(default=list),
        ),
    ]
