# Generated by Django 6.0.7 on 2026-09-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intelligence", "0015_semanticpackage_schema_dependencies"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatattachment",
            name="analysis_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatattachment",
            name="analysis_error",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="chatattachment",
            name="analysis_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chatattachment",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Recebido"),
                    ("analyzed", "Analisado"),
                    ("awaiting_model", "Aguardando modelo local"),
                    ("analyzing", "Analisando localmente"),
                    ("failed", "Análise indisponível"),
                    ("rejected", "Recusado"),
                ],
                default="received",
                max_length=20,
            ),
        ),
    ]
