# Generated by Django 6.0.8 on 2026-09-10

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0005_rename_operational_task_index"),
        ("intelligence", "0016_attachment_analysis_retry"),
    ]

    operations = [
        migrations.CreateModel(
            name="DominioCommunication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_id", models.CharField(max_length=64)),
                ("subject", apps.common.encryption.EncryptedTextField(blank=True)),
                ("type_code", models.CharField(blank=True, max_length=32)),
                ("status_code", models.CharField(blank=True, max_length=32)),
                ("is_read", models.BooleanField(default=False)),
                ("source_captured_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="communications",
                        to="intelligence.intelligenceconnector",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "company", "is_read", "source_captured_at"],
                        name="intelligenc_organiz_4b6f31_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "source_id"),
                        name="intelligence_unique_dominio_communication",
                    )
                ],
            },
        ),
    ]
