# Generated by Django 6.0.8 on 2026-09-15 23:50

from django.db import migrations, models


def mark_unproven_historical_calls(apps, schema_editor):
    audit = apps.get_model('intelligence', 'EgressAudit')
    audit.objects.filter(allowed=True).update(call_state='unknown')


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0021_encrypt_intelligenceconnector_odbc_dsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='egressaudit',
            name='cache_creation_input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='egressaudit',
            name='cache_read_input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='egressaudit',
            name='call_state',
            field=models.CharField(choices=[('denied', 'Bloqueada'), ('reserved', 'Reservada'), ('succeeded', 'Respondida'), ('unknown', 'Resultado incerto')], default='denied', max_length=16),
        ),
        migrations.AddField(
            model_name='egressaudit',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='egressaudit',
            name='input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='egressaudit',
            name='output_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(mark_unproven_historical_calls, migrations.RunPython.noop),
    ]
