# Generated by Django 6.0.8 on 2026-09-16 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0022_egressaudit_cache_creation_input_tokens_and_more'),
        ('platform', '0031_billingclosedeferral'),
    ]

    operations = [
        migrations.AddField(
            model_name='egressaudit',
            name='usage_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform.usageevent'),
        ),
        migrations.AddField(
            model_name='egressaudit',
            name='user_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egress_attempts', to='intelligence.message'),
        ),
    ]
