# Generated by Django 6.0.8 on 2026-09-16 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0023_egressaudit_usage_event_egressaudit_user_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='in_reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='intelligence.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='request_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
