# Generated by Django 6.0.8 on 2026-09-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0024_message_in_reply_to_message_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='egressaudit',
            name='provider_http_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='egressaudit',
            name='provider_request_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
