# Generated by Django 6.0.8 on 2026-09-16 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0025_egressaudit_provider_http_status_and_more'),
        ('platform', '0031_billingclosedeferral'),
    ]

    operations = [
        migrations.AddField(
            model_name='egressaudit',
            name='token_usage_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform.tokenusageevent'),
        ),
    ]
