# Generated by Django 6.0.8 on 2026-09-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0038_accountingexport_target_and_siescon_source"),
        ("intelligence", "0026_egress_audit_token_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgesource",
            name="area",
            field=models.CharField(
                choices=[
                    ("general", "Geral"),
                    ("accounting", "Contábil"),
                    ("fiscal", "Fiscal"),
                    ("payroll", "Folha"),
                ],
                default="general",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="knowledgesource",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intelligence_knowledge_sources",
                to="hub.clientcompany",
            ),
        ),
        migrations.AddField(
            model_name="knowledgesource",
            name="reference_period",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="trainingexample",
            name="area",
            field=models.CharField(
                choices=[
                    ("general", "Geral"),
                    ("accounting", "Contábil"),
                    ("fiscal", "Fiscal"),
                    ("payroll", "Folha"),
                ],
                default="general",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="trainingexample",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intelligence_training_examples",
                to="hub.clientcompany",
            ),
        ),
        migrations.AddField(
            model_name="trainingexample",
            name="reference_period",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
