# Generated by Django 6.0.8 on 2026-09-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intelligence", "0027_knowledgesource_area_knowledgesource_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationrun",
            name="adapter_artifact_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="evaluationrun",
            name="adapter_version",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="evaluationrun",
            name="base_model",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="evaluationrun",
            name="manifest_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="adapter_artifact_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="base_model",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="manifest_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
