# Generated by Django 6.0.8 on 2026-09-23 15:09

import apps.common.encryption
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0046_payroll_period_snapshots'),
        ('intelligence', '0029_evaluationrun_evaluation_manifest_sha256_and_more'),
        ('organizations', '0004_organization_is_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExportRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'XLSX')], max_length=8)),
                ('template_version', models.CharField(max_length=80)),
                ('snapshot', apps.common.encryption.EncryptedTextField()),
                ('snapshot_sha256', models.CharField(db_index=True, max_length=64)),
                ('output_sha256', models.CharField(max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hub.clientcompany')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_exports', to='intelligence.message')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'company', 'created_at'], name='intelligenc_organiz_c5a8c7_idx'), models.Index(fields=['message', 'created_at'], name='intelligenc_message_b0c680_idx')],
            },
        ),
    ]
