# Generated by Django 6.0.7 on 2026-07-29 03:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.audit.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("action", models.CharField(db_index=True, max_length=120)),
                ("target_type", models.CharField(blank=True, max_length=120)),
                ("target_id", models.CharField(blank=True, max_length=100)),
                ("request_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("success", models.BooleanField(default=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, validators=[apps.audit.models.validate_metadata]
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at",),
                "indexes": [
                    models.Index(
                        fields=["organization", "occurred_at"],
                        name="audit_audit_organiz_950f33_idx",
                    ),
                    models.Index(
                        fields=["actor", "occurred_at"], name="audit_audit_actor_i_023a4b_idx"
                    ),
                    models.Index(
                        fields=["action", "occurred_at"], name="audit_audit_action_7e10a4_idx"
                    ),
                ],
            },
        ),
    ]
