# Generated by Django 6.0.7 on 2026-09-15 01:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.common.encryption
import apps.triage.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hub", "0021_alter_productmodule_code_triage"),
        ("organizations", "0002_alter_membership_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64)),
                ("label", models.CharField(max_length=160)),
                ("name_template", models.CharField(max_length=200)),
                ("folder_template", models.CharField(blank=True, max_length=200)),
                (
                    "period_kind",
                    models.CharField(
                        choices=[
                            ("competencia", "Competência (mês)"),
                            ("intervalo", "Intervalo de datas"),
                            ("data_pagamento", "Data de pagamento"),
                            ("anual", "Anual"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "counterparty_kind",
                    models.CharField(
                        choices=[
                            ("nenhuma", "Nenhuma"),
                            ("banco", "Banco"),
                            ("instituicao", "Instituição financeira"),
                            ("imobiliaria", "Imobiliária"),
                            ("inquilino", "Inquilino"),
                        ],
                        default="nenhuma",
                        max_length=16,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("label",),
            },
        ),
        migrations.CreateModel(
            name="ChecklistExpectation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requirement",
                    models.CharField(
                        choices=[
                            ("expected", "Esperado"),
                            ("optional", "Opcional"),
                            ("waived", "Dispensado"),
                            ("not_applicable", "Não se aplica"),
                        ],
                        default="expected",
                        max_length=16,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triage_expectations",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expectations",
                        to="triage.documenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mailbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("ms365_graph", "Microsoft 365 (Graph)"), ("imap", "IMAP")],
                        max_length=16,
                    ),
                ),
                ("address", models.EmailField(max_length=254)),
                ("folder", models.CharField(default="INBOX", max_length=160)),
                ("credential", apps.common.encryption.EncryptedTextField(blank=True)),
                ("cursor", models.CharField(blank=True, max_length=255)),
                ("since", models.DateTimeField(blank=True, null=True)),
                ("sender_filter", models.CharField(blank=True, max_length=255)),
                ("subject_filter", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Aguardando autorização"),
                            ("active", "Ativa"),
                            ("error", "Com erro"),
                            ("disabled", "Desativada"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("last_polled_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=500)),
                ("active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TriageItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message_id", models.CharField(blank=True, max_length=255)),
                ("part_id", models.CharField(blank=True, max_length=64)),
                ("sender", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(blank=True, max_length=500)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("original_name", models.CharField(max_length=255)),
                ("content_hash", models.CharField(blank=True, db_index=True, max_length=64)),
                ("byte_size", models.PositiveBigIntegerField(default=0)),
                ("declared_type", models.CharField(blank=True, max_length=100)),
                ("detected_type", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recebido", "Recebido"),
                            ("em_quarentena", "Em quarentena"),
                            ("rejeitado", "Rejeitado"),
                            ("aguardando_extracao", "Aguardando extração"),
                            ("em_extracao", "Em extração"),
                            ("aguardando_revisao", "Aguardando revisão"),
                            ("pronto_para_arquivar", "Pronto para arquivar"),
                            ("falha", "Falha"),
                            ("arquivando", "Arquivando"),
                            ("arquivado", "Arquivado"),
                            ("falha_de_arquivamento", "Falha ao arquivar"),
                        ],
                        default="recebido",
                        max_length=24,
                    ),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("period_label", models.CharField(blank=True, max_length=16)),
                ("counterparty_token", models.CharField(blank=True, max_length=64)),
                ("final_name", models.CharField(blank=True, max_length=255)),
                ("ai_fields", models.JSONField(blank=True, default=dict)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=500)),
                (
                    "destination_kind",
                    models.CharField(
                        blank=True,
                        choices=[("internal", "Biblioteca interna"), ("windows", "Pastas Windows")],
                        max_length=16,
                    ),
                ),
                ("destination_path", models.CharField(blank=True, max_length=500)),
                ("destination_hash", models.CharField(blank=True, max_length=64)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="triage.documenttype",
                    ),
                ),
                (
                    "mailbox",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="triage.mailbox",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TriageBlob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.FileField(upload_to=apps.triage.models.private_triage_path)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "triage_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blob",
                        to="triage.triageitem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChecklistEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_label", models.CharField(max_length=16)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triage_checklist_entries",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_entries",
                        to="triage.documenttype",
                    ),
                ),
                (
                    "triage_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="triage.triageitem",
                    ),
                ),
            ],
            options={
                "ordering": ("-period_label",),
            },
        ),
        migrations.CreateModel(
            name="AgentFileJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("destination_path", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Na fila"),
                            ("claimed", "Reivindicado pelo agente"),
                            ("done", "Concluído"),
                            ("failed", "Falhou"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("claimed_by", models.CharField(blank=True, max_length=64)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.CharField(blank=True, max_length=500)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "triage_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_jobs",
                        to="triage.triageitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CounterpartyAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("nenhuma", "Nenhuma"),
                            ("banco", "Banco"),
                            ("instituicao", "Instituição financeira"),
                            ("imobiliaria", "Imobiliária"),
                            ("inquilino", "Inquilino"),
                        ],
                        max_length=16,
                    ),
                ),
                ("token", models.CharField(max_length=64)),
                ("alias", models.CharField(max_length=160)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("kind", "token"),
                "indexes": [
                    models.Index(
                        fields=["organization", "kind", "token"],
                        name="triage_coun_organiz_e9e5c2_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "kind", "alias"),
                        name="triage_unique_counterparty_alias",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DestinationProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("internal", "Biblioteca interna"), ("windows", "Pastas Windows")],
                        default="internal",
                        max_length=16,
                    ),
                ),
                ("windows_root", models.CharField(blank=True, max_length=500)),
                ("folder_template", models.CharField(blank=True, max_length=200)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triage_destination",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["organization", "created_at"], name="triage_dest_organiz_5a43dd_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="documenttype",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="triage_unique_document_type_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistexpectation",
            constraint=models.UniqueConstraint(
                fields=("company", "document_type"), name="triage_unique_expectation"
            ),
        ),
        migrations.AddIndex(
            model_name="mailbox",
            index=models.Index(
                fields=["organization", "active"], name="triage_mail_organiz_d243cc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mailbox",
            constraint=models.UniqueConstraint(
                fields=("organization", "provider", "address", "folder"),
                name="triage_unique_mailbox_per_office",
            ),
        ),
        migrations.AddIndex(
            model_name="triageitem",
            index=models.Index(
                fields=["organization", "status"], name="triage_tria_organiz_6d8b64_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="triageitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("mailbox__isnull", False), models.Q(("message_id", ""), _negated=True)
                ),
                fields=("mailbox", "message_id", "part_id"),
                name="triage_unique_mailbox_message_part",
            ),
        ),
        migrations.AddConstraint(
            model_name="triageitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("content_hash__gt", "")),
                fields=("organization", "content_hash"),
                name="triage_unique_content_hash_per_office",
            ),
        ),
        migrations.AddIndex(
            model_name="triageblob",
            index=models.Index(
                fields=["organization", "created_at"], name="triage_tria_organiz_4123fb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistentry",
            constraint=models.UniqueConstraint(
                fields=("company", "document_type", "period_label"),
                name="triage_unique_checklist_entry",
            ),
        ),
        migrations.AddIndex(
            model_name="agentfilejob",
            index=models.Index(
                fields=["organization", "status"], name="triage_agen_organiz_159c92_idx"
            ),
        ),
    ]
