# Generated by Django 6.0.8 on 2026-09-15 13:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.triage.models
import apps.triage.storage


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_alter_membership_role"),
        ("triage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="triageblob",
            name="content",
            field=models.FileField(
                storage=apps.triage.storage.PrivateTriageStorage(),
                upload_to=apps.triage.models.private_triage_path,
            ),
        ),
        migrations.CreateModel(
            name="TriageEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_status", models.CharField(max_length=24)),
                ("to_status", models.CharField(max_length=24)),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "triage_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="triage.triageitem",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "indexes": [
                    models.Index(
                        fields=["organization", "triage_item", "created_at"],
                        name="triage_tria_organiz_a4d6b1_idx",
                    )
                ],
            },
        ),
    ]
