# Generated by Django 6.0.8 on 2026-09-15 13:47

from django.db import migrations, models

import apps.common.encryption


def encrypt_existing_cursors(apps, schema_editor):
    mailbox_model = apps.get_model("triage", "Mailbox")
    for mailbox in mailbox_model.objects.using(schema_editor.connection.alias).exclude(cursor=""):
        mailbox.save(update_fields=["cursor"])


class Migration(migrations.Migration):
    dependencies = [
        ("triage", "0002_triage_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailbox",
            name="cursor",
            field=apps.common.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="mailbox",
            name="provider",
            field=models.CharField(
                choices=[
                    ("ms365_graph", "Microsoft 365 (Graph)"),
                    ("gmail_api", "Gmail / Google Workspace"),
                    ("imap", "IMAP"),
                ],
                max_length=16,
            ),
        ),
        migrations.RunPython(encrypt_existing_cursors, migrations.RunPython.noop),
    ]
