# Generated by Django 6.0.8 on 2026-09-15 20:13

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_membership_can_acknowledge_dte'),
        ('triage', '0003_alter_mailbox_cursor_alter_mailbox_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxOAuthApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('ms365_graph', 'Microsoft 365'), ('gmail_api', 'Gmail / Google Workspace')], max_length=16)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', apps.common.encryption.EncryptedTextField()),
                ('tenant_id', models.CharField(blank=True, max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
        migrations.AddField(
            model_name='mailbox',
            name='oauth_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailboxes', to='triage.mailboxoauthapp'),
        ),
        migrations.AddConstraint(
            model_name='mailboxoauthapp',
            constraint=models.UniqueConstraint(fields=('organization', 'provider'), name='triage_one_oauth_app_per_office_provider'),
        ),
    ]
