# Generated by Django 6.0.8 on 2026-09-15 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0026_dtemessageobservation_dtemessagestate_and_more'),
        ('organizations', '0003_membership_can_acknowledge_dte'),
        ('triage', '0004_mailboxoauthapp_mailbox_oauth_app_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='triageitem',
            name='triage_unique_content_hash_per_office',
        ),
        migrations.AddIndex(
            model_name='triageitem',
            index=models.Index(fields=['organization', 'content_hash'], name='triage_tria_organiz_ffc171_idx'),
        ),
    ]
