# Generated by Django 6.0.8 on 2026-09-15 21:08

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_membership_can_acknowledge_dte'),
        ('triage', '0005_remove_triageitem_triage_unique_content_hash_per_office_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageSafetyScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engine', models.CharField(blank=True, max_length=40)),
                ('verdict', models.CharField(choices=[('clean', 'Sem detecção'), ('infected', 'Ameaça detectada'), ('error', 'Varredura falhou')], max_length=16)),
                ('content_hash', models.CharField(max_length=64)),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('triage_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_scan', to='triage.triageitem')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['organization', 'created_at'], name='triage_tria_organiz_6fa0a0_idx')],
            },
        ),
    ]
