# Generated by Django 6.0.8 on 2026-09-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0006_triagesafetyscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='poll_lease_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='poll_lease_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
