# Generated by Django 6.0.8 on 2026-09-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0007_mailbox_poll_lease_token_mailbox_poll_lease_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='poll_failure_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='poll_retry_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
