# Generated by Django 6.0.8 on 2026-09-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0008_mailbox_poll_failure_count_mailbox_poll_retry_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagesafetyscan',
            name='format_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='triagesafetyscan',
            name='format_verdict',
            field=models.CharField(choices=[('pending', 'Formato pendente'), ('valid', 'Formato validado'), ('invalid', 'Formato recusado')], default='pending', max_length=16),
        ),
    ]
