# Generated by Django 6.0.8 on 2026-09-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0009_triagesafetyscan_format_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triageevent',
            name='from_status',
            field=models.CharField(choices=[('recebido', 'Recebido'), ('em_quarentena', 'Em quarentena'), ('rejeitado', 'Rejeitado'), ('aguardando_extracao', 'Aguardando extração'), ('em_extracao', 'Em extração'), ('aguardando_revisao', 'Aguardando revisão'), ('pronto_para_arquivar', 'Pronto para arquivar'), ('falha', 'Falha'), ('arquivando', 'Arquivando'), ('arquivado', 'Arquivado'), ('falha_de_arquivamento', 'Falha ao arquivar')], max_length=24),
        ),
        migrations.AlterField(
            model_name='triageevent',
            name='to_status',
            field=models.CharField(choices=[('recebido', 'Recebido'), ('em_quarentena', 'Em quarentena'), ('rejeitado', 'Rejeitado'), ('aguardando_extracao', 'Aguardando extração'), ('em_extracao', 'Em extração'), ('aguardando_revisao', 'Aguardando revisão'), ('pronto_para_arquivar', 'Pronto para arquivar'), ('falha', 'Falha'), ('arquivando', 'Arquivando'), ('arquivado', 'Arquivado'), ('falha_de_arquivamento', 'Falha ao arquivar')], max_length=24),
        ),
    ]
