# Generated by Django 6.0.8 on 2026-10-06 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0010_alter_triageevent_from_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triageevent',
            name='reason',
            field=models.CharField(blank=True, db_default='', default='', max_length=500),
        ),
        migrations.AddField(
            model_name='triageitem',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='triage.triageitem'),
        ),
        migrations.AddField(
            model_name='triageitem',
            name='pipeline_attempts',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
    ]
