# Generated by Django 6.0.7 on 2026-09-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Administrator"),
                    ("manager", "Manager"),
                    ("operator", "Operator"),
                    ("member", "Member (legacy)"),
                    ("billing", "Billing"),
                    ("auditor", "Auditor"),
                ],
                default="member",
                max_length=16,
            ),
        ),
    ]
