# Generated by Django 6.0.8 on 2026-09-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_membership_can_acknowledge_dte'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
