# Generated by Django 6.0.8 on 2026-09-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_internal_test_partner',
            field=models.BooleanField(default=False),
        ),
    ]
