# Generated by Django 6.0.8 on 2026-10-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0005_internal_test_partner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Dono"),
                    ("admin", "Administrador"),
                    ("manager", "Gestor"),
                    ("operator", "Operador"),
                    ("member", "Membro"),
                    ("billing", "Financeiro"),
                    ("auditor", "Auditor"),
                ],
                default="member",
                max_length=16,
            ),
        ),
    ]
