"""Prepare and optionally run a locally mounted LlamaFactory QLoRA job.

The runner consumes only two immutable artifacts exported by HubContador: the job
specification and a tenant-scoped JSONL manifest. It deliberately has no Django,
ODBC, Hub API, network client, secret or cloud-provider dependency.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
from collections.abc import Iterable, Mapping
from pathlib import Path

JOB_FORMAT = "hubcontador.lora-job.v1"
DATASET_NAME = "hubcontador_train"
MAX_MANIFEST_BYTES = 50 * 1024 * 1024
MAX_EXAMPLES = 100_000
_MODEL_NAME_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]{0,159}")
_ADAPTER_NAME_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]{0,119}")
_TEMPLATE_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]{0,79}")
_HASH_RE = re.compile(r"[a-f0-9]{64}")
_PERSONAL_DATA_RE = re.compile(
    r"\b\d{3}\.?\d{3}\.?\d{3}-?\d{2}\b|\b\d{2}\.?\d{3}\.?\d{3}/?\d{4}-?\d{2}\b|"
    r"\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b",
    re.IGNORECASE,
)
_SYSTEM_PROMPT = (
    "Você é o Assistente IA do HubContador. Responda em português, use somente fontes "
    "aprovadas, declare incerteza quando faltar evidência e nunca revele raciocínio interno."
)


class TrainingRunnerError(ValueError):
    """The immutable job artifact is unsafe, stale or incompatible."""


def _canonical_json(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def _required_string(item: Mapping[str, object], field: str, limit: int) -> str:
    value = item.get(field)
    if not isinstance(value, str) or not value or len(value) > limit:
        raise TrainingRunnerError(f"Campo de corpus inválido: {field}.")
    return value


def load_job_spec(path: Path) -> dict[str, object]:
    """Load the minimal, strict QLoRA contract generated by HubContador."""
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise TrainingRunnerError("Especificação de treinamento inválida.") from exc
    if not isinstance(payload, dict) or payload.get("format") != JOB_FORMAT:
        raise TrainingRunnerError("Formato de especificação de treinamento não suportado.")
    manifest_hash = payload.get("manifest_sha256")
    if not isinstance(manifest_hash, str) or not _HASH_RE.fullmatch(manifest_hash):
        raise TrainingRunnerError("Hash de corpus ausente ou inválido.")
    example_count = payload.get("example_count")
    if not isinstance(example_count, int) or not 1 <= example_count <= MAX_EXAMPLES:
        raise TrainingRunnerError("Quantidade de exemplos inválida.")
    if payload.get("method") != "qlora":
        raise TrainingRunnerError("Apenas treinamento QLoRA é permitido.")
    for field, pattern in {
        "base_model": _MODEL_NAME_RE,
        "adapter_name": _ADAPTER_NAME_RE,
        "chat_template": _TEMPLATE_RE,
    }.items():
        value = payload.get(field)
        if not isinstance(value, str) or not pattern.fullmatch(value):
            raise TrainingRunnerError(f"Campo de job inválido: {field}.")
    training = payload.get("training")
    if not isinstance(training, dict):
        raise TrainingRunnerError("Parâmetros de treinamento ausentes.")
    if training != {
        "max_seq_length": 4096,
        "epochs": 3,
        "learning_rate": 0.0001,
        "quantization": "4bit-nf4",
    }:
        raise TrainingRunnerError("Parâmetros de treinamento fora da política aprovada.")
    return payload


def load_manifest(path: Path) -> list[dict[str, object]]:
    """Read a bounded, source-linked JSONL artifact and reject identifiers."""
    try:
        if path.stat().st_size > MAX_MANIFEST_BYTES:
            raise TrainingRunnerError("Corpus excede o limite permitido.")
        lines = path.read_text(encoding="utf-8").splitlines()
    except (OSError, UnicodeDecodeError) as exc:
        raise TrainingRunnerError("Não foi possível ler o corpus de treinamento.") from exc
    if not 1 <= len(lines) <= MAX_EXAMPLES:
        raise TrainingRunnerError("Quantidade de linhas do corpus inválida.")
    items: list[dict[str, object]] = []
    for line in lines:
        try:
            item = json.loads(line)
        except json.JSONDecodeError as exc:
            raise TrainingRunnerError("Corpus contém JSON inválido.") from exc
        if not isinstance(item, dict):
            raise TrainingRunnerError("Corpus contém um exemplo inválido.")
        validated = {
            "id": _required_string(item, "id", 64),
            "category": _required_string(item, "category", 20),
            "question": _required_string(item, "question", 2_000),
            "expected_answer": _required_string(item, "expected_answer", 4_000),
            "source_references": item.get("source_references"),
            "scenario_hash": _required_string(item, "scenario_hash", 64),
        }
        references = validated["source_references"]
        if (
            not isinstance(references, list)
            or not 1 <= len(references) <= 8
            or any(not isinstance(reference, str) or not reference for reference in references)
        ):
            raise TrainingRunnerError("Exemplo sem fontes aprovadas.")
        if not _HASH_RE.fullmatch(str(validated["scenario_hash"])):
            raise TrainingRunnerError("Hash de cenário inválido.")
        serialized = _canonical_json(validated)
        if _PERSONAL_DATA_RE.search(serialized):
            raise TrainingRunnerError(
                "Corpus contém identificador pessoal; anonimize antes do treino."
            )
        items.append(validated)
    return items


def manifest_sha256(items: Iterable[Mapping[str, object]]) -> str:
    """Match the canonical fingerprint produced by ``training.corpus_fingerprint``."""
    canonical = _canonical_json(list(items))
    return hashlib.sha256(canonical.encode()).hexdigest()


def _under_root(path: Path, root: Path) -> Path:
    resolved_root = root.resolve()
    resolved_path = path.resolve()
    if resolved_path != resolved_root and resolved_root not in resolved_path.parents:
        raise TrainingRunnerError("Caminho fora do volume permitido.")
    return resolved_path


def prepare_workspace(
    *,
    job_spec: Mapping[str, object],
    manifest: list[dict[str, object]],
    workspace: Path,
    models_root: Path,
) -> Path:
    """Create LlamaFactory's Alpaca dataset/configuration without starting training."""
    if manifest_sha256(manifest) != job_spec["manifest_sha256"]:
        raise TrainingRunnerError("O corpus não corresponde ao hash do job aprovado.")
    if len(manifest) != job_spec["example_count"]:
        raise TrainingRunnerError("A contagem do corpus não corresponde ao job aprovado.")
    root = workspace.resolve()
    data_directory = _under_root(root / "data", root)
    output_directory = _under_root(root / "output", root)
    if output_directory.exists() and any(output_directory.iterdir()):
        raise TrainingRunnerError("A saída do adaptador já existe; use um diretório vazio.")
    base_model = str(job_spec["base_model"])
    model_path = _under_root(models_root / base_model, models_root)
    if not model_path.is_dir():
        raise TrainingRunnerError("Modelo base local não está montado no volume permitido.")
    data_directory.mkdir(parents=True, exist_ok=True)
    output_directory.mkdir(parents=True, exist_ok=True)
    dataset_path = data_directory / "training.jsonl"
    with dataset_path.open("w", encoding="utf-8", newline="\n") as stream:
        for item in manifest:
            source_references = item["source_references"]
            assert isinstance(source_references, list)
            references = "; ".join(str(value) for value in source_references)
            record = {
                "instruction": item["question"],
                "input": f"Fontes aprovadas: {references}",
                "output": item["expected_answer"],
                "system": _SYSTEM_PROMPT,
            }
            stream.write(json.dumps(record, ensure_ascii=False, separators=(",", ":")) + "\n")
    (data_directory / "dataset_info.json").write_text(
        json.dumps(
            {
                DATASET_NAME: {
                    "file_name": dataset_path.name,
                    "columns": {
                        "prompt": "instruction",
                        "query": "input",
                        "response": "output",
                        "system": "system",
                    },
                }
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    config_path = root / "train.yaml"
    config_path.write_text(
        "\n".join(
            [
                f"model_name_or_path: {model_path}",
                "stage: sft",
                "do_train: true",
                "finetuning_type: lora",
                "quantization_bit: 4",
                f"dataset_dir: {data_directory}",
                f"dataset: {DATASET_NAME}",
                f"template: {job_spec['chat_template']}",
                "cutoff_len: 4096",
                "learning_rate: 0.0001",
                "num_train_epochs: 3.0",
                f"output_dir: {output_directory}",
                "overwrite_output_dir: false",
                "save_only_model: true",
                "report_to: none",
                "",
            ]
        ),
        encoding="utf-8",
    )
    return config_path


def run_training(*, config_path: Path, workspace: Path) -> None:
    """Run only the installed local CLI; never execute through a shell."""
    executable = os.environ.get("LLAMAFACTORY_EXECUTABLE", "llamafactory-cli")
    if not shutil.which(executable):
        raise TrainingRunnerError("LlamaFactory não está disponível na imagem aprovada.")
    subprocess.run([executable, "train", str(config_path)], cwd=workspace, check=True)  # noqa: S603


def main() -> None:
    parser = argparse.ArgumentParser(description="Runner QLoRA offline do HubContador")
    parser.add_argument("--job", type=Path, required=True)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--workspace", type=Path, required=True)
    parser.add_argument("--models-root", type=Path, required=True)
    parser.add_argument("--execute", action="store_true", help="Executa o CLI local após validar")
    arguments = parser.parse_args()
    job_spec = load_job_spec(arguments.job)
    manifest = load_manifest(arguments.manifest)
    config_path = prepare_workspace(
        job_spec=job_spec,
        manifest=manifest,
        workspace=arguments.workspace,
        models_root=arguments.models_root,
    )
    if arguments.execute:
        if os.environ.get("HUB_TRAINING_EXECUTION_APPROVED") != "1":
            raise TrainingRunnerError(
                "Defina HUB_TRAINING_EXECUTION_APPROVED=1 para iniciar treino."
            )
        run_training(config_path=config_path, workspace=arguments.workspace)
    print(
        json.dumps(
            {"status": "prepared", "config": str(config_path), "executed": arguments.execute}
        )
    )


if __name__ == "__main__":
    main()
