# Generated by Django 6.0.8 on 2026-09-22 17:11

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hub", "0039_onboarding_progress"),
        ("organizations", "0004_organization_is_demo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Colaborador",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(blank=True, max_length=24)),
                (
                    "contratacao",
                    models.CharField(
                        choices=[("clt", "CLT"), ("pj", "PJ")], default="clt", max_length=3
                    ),
                ),
                ("nome", apps.common.encryption.EncryptedTextField()),
                ("nome_bi", models.CharField(db_index=True, max_length=64)),
                ("cargo", models.CharField(blank=True, max_length=80)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "origem",
                    models.CharField(
                        choices=[("dominio", "Domínio"), ("manual", "Manual")],
                        default="manual",
                        max_length=8,
                    ),
                ),
                ("i_empregados", models.IntegerField(blank=True, null=True)),
                (
                    "beneficios_mensais",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("vt_mensal", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "outros_custos_mensais",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("dias_ferias", models.PositiveSmallIntegerField(default=22)),
                ("folgas_dias", models.PositiveSmallIntegerField(default=0)),
                ("ausencias_dias", models.PositiveSmallIntegerField(default=0)),
                (
                    "empresa_folha",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profitability_colaboradores_folha",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("codigo",),
            },
        ),
        migrations.CreateModel(
            name="ColaboradorCompetenciaMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competencia",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use o formato AAAA-MM.", regex="^\\d{4}-(0[1-9]|1[0-2])$"
                            )
                        ],
                    ),
                ),
                ("horas_auto_minutos", models.IntegerField(default=0)),
                ("horas_f9_minutos", models.IntegerField(default=0)),
                ("diferenca_minutos", models.IntegerField(default=0)),
                ("custo", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("custo_hora", models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ("sem_salario", models.BooleanField(default=False)),
                ("empresas_count", models.IntegerField(default=0)),
                ("f9_pendente", models.BooleanField(default=False)),
                ("divergente", models.BooleanField(default=False)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metricas",
                        to="profitability.colaborador",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("-competencia",),
            },
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competencia",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use o formato AAAA-MM.", regex="^\\d{4}-(0[1-9]|1[0-2])$"
                            )
                        ],
                    ),
                ),
                ("inicio", models.DateField()),
                ("fim", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("aberta", "Aberta"), ("fechada", "Fechada")],
                        default="aberta",
                        max_length=8,
                    ),
                ),
                ("is_atual", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("-competencia",),
            },
        ),
        migrations.CreateModel(
            name="EventoFaturamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("codi_emp_origem", models.IntegerField()),
                ("i_evento", models.IntegerField()),
                (
                    "competencia",
                    models.CharField(
                        db_index=True,
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use o formato AAAA-MM.", regex="^\\d{4}-(0[1-9]|1[0-2])$"
                            )
                        ],
                    ),
                ),
                ("lancamentos", models.PositiveIntegerField(default=0)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("-competencia", "-total"),
            },
        ),
        migrations.CreateModel(
            name="Mensalidade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competencia",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use o formato AAAA-MM.", regex="^\\d{4}-(0[1-9]|1[0-2])$"
                            )
                        ],
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "fonte",
                    models.CharField(
                        choices=[("dominio", "Domínio"), ("manual", "Manual")], max_length=8
                    ),
                ),
                (
                    "manual_override",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profitability_mensalidades",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("-competencia",),
            },
        ),
        migrations.CreateModel(
            name="ProfitabilityConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "margem_alvo_padrao",
                    models.DecimalField(decimal_places=4, default=Decimal("0.2000"), max_digits=5),
                ),
                ("margem_alvo_global", models.BooleanField(default=False)),
                (
                    "margem_atencao",
                    models.DecimalField(decimal_places=4, default=Decimal("0.1500"), max_digits=5),
                ),
                ("minutos_minimos_custo", models.PositiveSmallIntegerField(default=10)),
                (
                    "encargos_percentual",
                    models.DecimalField(decimal_places=4, default=Decimal("0.3500"), max_digits=5),
                ),
                ("dias_uteis_ano", models.PositiveSmallIntegerField(default=250)),
                ("feriados_dias_ano", models.PositiveSmallIntegerField(default=10)),
                (
                    "horas_dia",
                    models.DecimalField(decimal_places=2, default=Decimal("8.00"), max_digits=4),
                ),
                (
                    "indice_produtividade",
                    models.DecimalField(decimal_places=4, default=Decimal("0.8000"), max_digits=5),
                ),
                ("limiar_divergencia_horas", models.PositiveSmallIntegerField(default=2)),
                ("limiar_divergencia_colaborador", models.PositiveSmallIntegerField(default=10)),
                ("codi_emp_confirmed", models.BooleanField(default=False)),
                (
                    "fonte_receita",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("billing_honorarios", "Domínio Honorários"),
                            ("billing_services", "Domínio Escrita Fiscal"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("evento_mensalidade", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profitability_config",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SalarioColaborador",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competencia",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use o formato AAAA-MM.", regex="^\\d{4}-(0[1-9]|1[0-2])$"
                            )
                        ],
                    ),
                ),
                ("salario", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "fonte",
                    models.CharField(
                        choices=[("dominio", "Domínio"), ("manual", "Manual")], max_length=8
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salarios",
                        to="profitability.colaborador",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("-competencia",),
            },
        ),
        migrations.CreateModel(
            name="Segmento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=80)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="CompanyErpProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("codi_emp", models.IntegerField(blank=True, null=True)),
                (
                    "origem",
                    models.CharField(
                        choices=[("dominio", "Domínio"), ("manual", "Manual")],
                        default="dominio",
                        max_length=8,
                    ),
                ),
                (
                    "sistema_origem",
                    models.CharField(
                        choices=[("dominio", "Domínio Sistemas"), ("siescon", "Siescon")],
                        default="dominio",
                        max_length=16,
                    ),
                ),
                ("documento", apps.common.encryption.EncryptedTextField(blank=True, default="")),
                ("documento_bi", models.CharField(blank=True, db_index=True, max_length=64)),
                ("documento_raiz_bi", models.CharField(blank=True, db_index=True, max_length=64)),
                ("documento_tipo", models.CharField(blank=True, max_length=8)),
                (
                    "razao_normalizada_bi",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("papel", models.JSONField(blank=True, default=list)),
                ("codigo", models.CharField(blank=True, max_length=24)),
                ("regime", models.CharField(blank=True, max_length=40)),
                ("regime_codigo", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("regime_vigencia", models.DateField(blank=True, null=True)),
                (
                    "margem_alvo",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
                ),
                (
                    "correspondencia",
                    models.CharField(
                        choices=[
                            ("cpf_cnpj", "Confirmado"),
                            ("razao_social", "Revisar correspondência"),
                            ("nao_encontrado", "Não localizado"),
                        ],
                        default="nao_encontrado",
                        max_length=16,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "empresa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="erp_profile",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="empresas_responsavel",
                        to="profitability.colaborador",
                    ),
                ),
                (
                    "segmento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="empresas",
                        to="profitability.segmento",
                    ),
                ),
            ],
            options={
                "ordering": ("codi_emp",),
            },
        ),
        migrations.CreateModel(
            name="ServicoFaturado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("codi_emp_origem", models.IntegerField()),
                ("codi_cli", models.IntegerField()),
                ("nome_cli", apps.common.encryption.EncryptedTextField(blank=True, default="")),
                (
                    "documento_cli",
                    apps.common.encryption.EncryptedTextField(blank=True, default=""),
                ),
                ("documento_cli_bi", models.CharField(blank=True, db_index=True, max_length=64)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("data_servico", models.DateField(blank=True, null=True)),
                ("source_id", models.CharField(max_length=128)),
                (
                    "competencia",
                    models.CharField(
                        db_index=True,
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use o formato AAAA-MM.", regex="^\\d{4}-(0[1-9]|1[0-2])$"
                            )
                        ],
                    ),
                ),
                (
                    "forma_localizacao",
                    models.CharField(
                        choices=[
                            ("cpf_cnpj", "Confirmado"),
                            ("razao_social", "Revisar correspondência"),
                            ("nao_encontrado", "Não localizado"),
                        ],
                        max_length=16,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profitability_servicos",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("competencia", "codi_cli"),
            },
        ),
        migrations.CreateModel(
            name="UsuarioErp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("i_usuario", models.CharField(max_length=64)),
                (
                    "sistema_origem",
                    models.CharField(
                        choices=[("dominio", "Domínio Sistemas"), ("siescon", "Siescon")],
                        default="dominio",
                        max_length=16,
                    ),
                ),
                ("nome", apps.common.encryption.EncryptedTextField()),
                ("nome_bi", models.CharField(db_index=True, max_length=64)),
                ("situacao", models.IntegerField(default=1)),
                ("ativo", models.BooleanField(default=True)),
                ("vinculo_manual", models.BooleanField(default=False)),
                (
                    "colaborador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usuarios_erp",
                        to="profitability.colaborador",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("i_usuario",),
            },
        ),
        migrations.CreateModel(
            name="RegistroHoras",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competencia",
                    models.CharField(
                        db_index=True,
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use o formato AAAA-MM.", regex="^\\d{4}-(0[1-9]|1[0-2])$"
                            )
                        ],
                    ),
                ),
                ("data", models.DateField()),
                (
                    "origem",
                    models.CharField(
                        choices=[("automatica", "Automática"), ("f9", "F9")], max_length=12
                    ),
                ),
                ("inicio", models.TimeField(blank=True, null=True)),
                ("fim", models.TimeField(blank=True, null=True)),
                ("data_fim", models.DateField(blank=True, null=True)),
                (
                    "duracao_minutos",
                    models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
                ),
                ("descricao", models.TextField(blank=True)),
                ("source_content_hash", models.CharField(max_length=64)),
                ("occurrence_index", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Conferido"),
                            ("divergente", "Divergente"),
                            ("pendente", "Pendente"),
                        ],
                        default="ok",
                        max_length=12,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "colaborador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_horas",
                        to="profitability.colaborador",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profitability_registros_horas",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "usuario_erp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros",
                        to="profitability.usuarioerp",
                    ),
                ),
            ],
            options={
                "ordering": ("data", "inicio"),
            },
        ),
        migrations.CreateModel(
            name="ClienteCompetenciaMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competencia",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use o formato AAAA-MM.", regex="^\\d{4}-(0[1-9]|1[0-2])$"
                            )
                        ],
                    ),
                ),
                ("horas_auto_minutos", models.IntegerField(default=0)),
                ("horas_f9_minutos", models.IntegerField(default=0)),
                ("custo", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("mensalidade", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("resultado", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("margem", models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                (
                    "faixa",
                    models.CharField(
                        choices=[
                            ("negativa", "Margem negativa"),
                            ("atencao", "Atenção"),
                            ("saudavel", "Saudável"),
                            ("sem_dados", "Sem dados"),
                            ("incompleta", "Custo incompleto"),
                        ],
                        max_length=12,
                    ),
                ),
                ("custo_completo", models.BooleanField(default=True)),
                ("minutos_sem_custo", models.IntegerField(default=0)),
                ("motivos_incompletude", models.JSONField(blank=True, default=list)),
                ("divergencia_minutos", models.IntegerField(default=0)),
                ("tem_divergencia", models.BooleanField(default=False)),
                ("f9_pendente", models.BooleanField(default=False)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profitability_metricas",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("-competencia",),
                "indexes": [
                    models.Index(
                        fields=["organization", "competencia", "faixa"],
                        name="profitabili_organiz_c6aacc_idx",
                    ),
                    models.Index(
                        fields=["organization", "competencia", "margem"],
                        name="profitabili_organiz_5b19f3_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("empresa", "competencia"),
                        name="profitability_unique_cliente_metrics",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="colaborador",
            index=models.Index(
                fields=["organization", "ativo"], name="profitabili_organiz_3d4d19_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="colaborador",
            constraint=models.UniqueConstraint(
                condition=models.Q(("i_empregados__isnull", False)),
                fields=("organization", "empresa_folha", "i_empregados"),
                name="profitability_unique_colaborador_erp",
            ),
        ),
        migrations.AddIndex(
            model_name="colaboradorcompetenciametrics",
            index=models.Index(
                fields=["organization", "competencia", "divergente"],
                name="profitabili_organiz_612c84_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="colaboradorcompetenciametrics",
            constraint=models.UniqueConstraint(
                fields=("colaborador", "competencia"),
                name="profitability_unique_colaborador_metrics",
            ),
        ),
        migrations.AddConstraint(
            model_name="competencia",
            constraint=models.UniqueConstraint(
                fields=("organization", "competencia"), name="profitability_unique_competencia"
            ),
        ),
        migrations.AddConstraint(
            model_name="competencia",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_atual", True)),
                fields=("organization",),
                name="profitability_unique_competencia_atual",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventofaturamento",
            constraint=models.UniqueConstraint(
                fields=("organization", "codi_emp_origem", "i_evento", "competencia"),
                name="profitability_unique_evento_faturamento",
            ),
        ),
        migrations.AddConstraint(
            model_name="mensalidade",
            constraint=models.UniqueConstraint(
                fields=("empresa", "competencia"),
                name="profitability_unique_mensalidade_competencia",
            ),
        ),
        migrations.AddConstraint(
            model_name="salariocolaborador",
            constraint=models.UniqueConstraint(
                fields=("organization", "colaborador", "competencia"),
                name="profitability_unique_salario_competencia",
            ),
        ),
        migrations.AddConstraint(
            model_name="segmento",
            constraint=models.UniqueConstraint(
                fields=("organization", "nome"), name="profitability_unique_segmento_nome"
            ),
        ),
        migrations.AddIndex(
            model_name="companyerpprofile",
            index=models.Index(
                fields=["organization", "documento_bi"], name="profitabili_organiz_3b4569_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyerpprofile",
            index=models.Index(
                fields=["organization", "documento_raiz_bi"], name="profitabili_organiz_1c0bb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyerpprofile",
            index=models.Index(
                fields=["organization", "razao_normalizada_bi"],
                name="profitabili_organiz_602f4d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="companyerpprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("codi_emp__isnull", False)),
                fields=("organization", "sistema_origem", "codi_emp"),
                name="profitability_unique_empresa_codi_emp",
            ),
        ),
        migrations.AddIndex(
            model_name="servicofaturado",
            index=models.Index(
                fields=["organization", "competencia", "empresa"],
                name="profitabili_organiz_999c68_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicofaturado",
            constraint=models.UniqueConstraint(
                fields=("organization", "source_id"), name="profitability_unique_servico_faturado"
            ),
        ),
        migrations.AddConstraint(
            model_name="usuarioerp",
            constraint=models.UniqueConstraint(
                fields=("organization", "sistema_origem", "i_usuario"),
                name="profitability_unique_usuario_erp",
            ),
        ),
        migrations.AddIndex(
            model_name="registrohoras",
            index=models.Index(
                fields=["organization", "competencia", "empresa"],
                name="profitabili_organiz_22600e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="registrohoras",
            index=models.Index(
                fields=["organization", "competencia", "colaborador"],
                name="profitabili_organiz_a36bf9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="registrohoras",
            index=models.Index(
                fields=["organization", "competencia", "origem"],
                name="profitabili_organiz_3b564f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrohoras",
            constraint=models.UniqueConstraint(
                fields=("organization", "source_content_hash", "occurrence_index"),
                name="profitability_unique_registro_horas_occurrence",
            ),
        ),
    ]
