# Generated by Django 6.0.8 on 2026-09-22 17:29

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0039_onboarding_progress"),
        ("organizations", "0004_organization_is_demo"),
        ("profitability", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_system",
                    models.CharField(
                        choices=[("dominio", "Domínio Sistemas"), ("siescon", "Siescon")],
                        max_length=16,
                    ),
                ),
                ("dataset_code", models.CharField(max_length=64)),
                ("schema_version", models.PositiveSmallIntegerField()),
                ("query_sha256", models.CharField(max_length=64)),
                ("manifest_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "run_kind",
                    models.CharField(
                        choices=[("full", "Completa"), ("incremental", "Incremental")],
                        max_length=12,
                    ),
                ),
                ("parameters", models.JSONField(default=list)),
                ("idempotency_key", models.CharField(max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("receiving", "Recebendo"),
                            ("processing", "Processando"),
                            ("succeeded", "Concluído"),
                            ("failed", "Falhou"),
                        ],
                        default="receiving",
                        max_length=12,
                    ),
                ),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("batch_count", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("rejected_count", models.PositiveIntegerField(default=0)),
                ("rejection_sample", models.JSONField(blank=True, default=list)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profitability_runs",
                        to="hub.connector",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="IngestBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                ("row_count", models.PositiveSmallIntegerField()),
                ("checksum_sha256", models.CharField(max_length=64)),
                ("payload", apps.common.encryption.EncryptedTextField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="profitability.ingestrun",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence",),
            },
        ),
        migrations.AddField(
            model_name="colaborador",
            name="last_seen_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="colaboradores_vistos",
                to="profitability.ingestrun",
            ),
        ),
        migrations.AddField(
            model_name="companyerpprofile",
            name="last_seen_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empresas_vistas",
                to="profitability.ingestrun",
            ),
        ),
        migrations.AddField(
            model_name="eventofaturamento",
            name="last_seen_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eventos_vistos",
                to="profitability.ingestrun",
            ),
        ),
        migrations.AddField(
            model_name="registrohoras",
            name="last_seen_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="horas_vistas",
                to="profitability.ingestrun",
            ),
        ),
        migrations.AddField(
            model_name="salariocolaborador",
            name="last_seen_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="salarios_vistos",
                to="profitability.ingestrun",
            ),
        ),
        migrations.AddField(
            model_name="servicofaturado",
            name="last_seen_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="servicos_vistos",
                to="profitability.ingestrun",
            ),
        ),
        migrations.AddField(
            model_name="usuarioerp",
            name="last_seen_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios_vistos",
                to="profitability.ingestrun",
            ),
        ),
        migrations.AddIndex(
            model_name="ingestrun",
            index=models.Index(
                fields=["organization", "status", "created_at"],
                name="profitabili_organiz_485437_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestrun",
            constraint=models.UniqueConstraint(
                fields=("organization", "connector", "idempotency_key"),
                name="profitability_unique_run_idempotency",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestbatch",
            constraint=models.UniqueConstraint(
                fields=("run", "sequence"), name="profitability_unique_batch_sequence"
            ),
        ),
    ]
