# Generated by Django 6.0.8 on 2026-09-22 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0039_onboarding_progress"),
        ("organizations", "0004_organization_is_demo"),
        ("profitability", "0002_ingestao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyerpprofile",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="erp_profiles",
                to="hub.clientcompany",
            ),
        ),
        migrations.AddConstraint(
            model_name="companyerpprofile",
            constraint=models.UniqueConstraint(
                fields=("empresa", "sistema_origem"), name="profitability_unique_empresa_por_erp"
            ),
        ),
    ]
