# Generated by Django 6.0.7 on 2026-07-29 03:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.common.encryption
import apps.privacy.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalDataIncident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=40, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("investigating", "Investigating"),
                            ("contained", "Contained"),
                            ("notifying", "Notifying"),
                            ("closed", "Closed"),
                        ],
                        default="investigating",
                        max_length=20,
                    ),
                ),
                ("discovered_at", models.DateTimeField()),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("contains_personal_data", models.BooleanField(default=False)),
                ("relevant_risk_or_harm", models.BooleanField(default=False)),
                ("summary", apps.common.encryption.EncryptedTextField()),
                ("risk_assessment", apps.common.encryption.EncryptedTextField(blank=True)),
                ("data_categories", models.JSONField(default=list)),
                (
                    "approximate_subject_count",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "notification_deadline_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set after legal review; ANPD Resolution 15/2024 generally uses 3 business days.",
                        null=True,
                    ),
                ),
                ("anpd_notified_at", models.DateTimeField(blank=True, null=True)),
                ("subjects_notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retain_until",
                    models.DateTimeField(
                        db_index=True, default=apps.privacy.models.incident_retention_target
                    ),
                ),
            ],
            options={
                "ordering": ("-discovered_at",),
            },
        ),
        migrations.CreateModel(
            name="PrivacyNotice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(max_length=32, unique=True)),
                ("document_url", models.URLField()),
                ("checksum_sha256", models.CharField(max_length=64)),
                ("effective_at", models.DateTimeField()),
                ("active", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-effective_at",),
            },
        ),
        migrations.CreateModel(
            name="ProcessingPurpose",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField()),
                (
                    "lawful_basis",
                    models.CharField(
                        choices=[
                            ("consent", "Consent"),
                            ("legal_obligation", "Legal or regulatory obligation"),
                            ("contract", "Contract performance"),
                            ("legitimate_interest", "Legitimate interest"),
                            ("exercise_of_rights", "Exercise of rights"),
                            ("credit_protection", "Credit protection"),
                            ("life_protection", "Protection of life"),
                            ("health", "Protection of health"),
                            ("research", "Research"),
                            ("public_policy", "Public policy"),
                        ],
                        max_length=32,
                    ),
                ),
                ("data_categories", models.JSONField(default=list)),
                ("retention_days", models.PositiveIntegerField()),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="DataSubjectRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("confirmation", "Confirmation of processing"),
                            ("access", "Access"),
                            ("correction", "Correction"),
                            ("anonymization", "Anonymization"),
                            ("blocking", "Blocking"),
                            ("deletion", "Deletion"),
                            ("portability", "Portability"),
                            ("consent_withdrawal", "Consent withdrawal"),
                            ("sharing_information", "Sharing information"),
                            ("automated_review", "Automated decision review"),
                            ("opposition", "Opposition"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("verifying", "Verifying identity"),
                            ("in_progress", "In progress"),
                            ("legal_review", "Legal review"),
                            ("completed", "Completed"),
                            ("denied", "Denied"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="received",
                        max_length=24,
                    ),
                ),
                ("details", apps.common.encryption.EncryptedTextField(blank=True)),
                ("response_summary", apps.common.encryption.EncryptedTextField(blank=True)),
                (
                    "target_due_at",
                    models.DateTimeField(
                        db_index=True, default=apps.privacy.models.privacy_request_target
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("denial_reason_code", models.CharField(blank=True, max_length=80)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_subject_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "target_due_at"], name="privacy_dat_status_1c90b8_idx"
                    ),
                    models.Index(
                        fields=["requester", "created_at"], name="privacy_dat_request_a336fc_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "idempotency_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("granted", "Granted"), ("withdrawn", "Withdrawn")], max_length=16
                    ),
                ),
                ("source", models.CharField(default="api", max_length=32)),
                ("recorded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_records",
                        to="privacy.privacynotice",
                    ),
                ),
                (
                    "purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_records",
                        to="privacy.processingpurpose",
                    ),
                ),
            ],
            options={
                "ordering": ("-recorded_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "purpose", "recorded_at"],
                        name="privacy_con_user_id_e9b5b1_idx",
                    )
                ],
            },
        ),
    ]
