# Generated by Django 6.0.7 on 2026-09-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("platform", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="supportsession", name="company_ids", field=models.JSONField(default=list)
        ),
        migrations.AddField(
            model_name="supportsession",
            name="control_grant_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
