# Generated by Django 6.0.7 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("platform", "0002_supportsession_company_ids_and_more")]

    operations = [
        migrations.AddField(
            model_name="supportsession",
            name="access_mode",
            field=models.CharField(
                choices=[("read_only", "Somente leitura"), ("full", "Teste completo")],
                default="read_only",
                max_length=16,
            ),
        ),
    ]
