# Generated by Django 6.0.8 on 2026-09-11 13:01

import django.core.validators
from django.db import migrations

import apps.common.encryption


def encrypt_existing_leads(apps, schema_editor):
    """Rewrite rows captured before the columns were encrypted.

    decrypt_text() passes a value through untouched when it carries no ciphertext prefix,
    and encrypt_text() skips a value that already has one, so this is safe to re-run.
    """

    Lead = apps.get_model("platform", "Lead")
    for lead in Lead.objects.using(schema_editor.connection.alias).iterator():
        lead.save(
            using=schema_editor.connection.alias,
            update_fields=["office_name", "contact_name", "contact_email", "message"],
        )


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0003_supportsession_access_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="contact_email",
            field=apps.common.encryption.EncryptedTextField(
                validators=[django.core.validators.EmailValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="contact_name",
            field=apps.common.encryption.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="lead",
            name="message",
            field=apps.common.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="office_name",
            field=apps.common.encryption.EncryptedTextField(),
        ),
        migrations.RunPython(encrypt_existing_leads, migrations.RunPython.noop),
    ]
