# Generated by Django 6.0.8 on 2026-09-12 13:15

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_alter_membership_role"),
        ("platform", "0004_encrypt_lead_contact_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="monthly_price_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("due_on", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Em aberto"),
                            ("paid", "Paga"),
                            ("overdue", "Vencida"),
                            ("void", "Cancelada"),
                            ("disputed", "Em contestação"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("base_amount_cents", models.PositiveIntegerField(default=0)),
                ("overage_amount_cents", models.PositiveIntegerField(default=0)),
                ("adjustment_amount_cents", models.IntegerField(default=0)),
                ("total_amount_cents", models.PositiveIntegerField(default=0)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="platform.tenantcontract",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("subscription", "Mensalidade"),
                            ("overage", "Excedente"),
                            ("adjustment", "Ajuste"),
                        ],
                        max_length=16,
                    ),
                ),
                ("action_code", models.CharField(blank=True, max_length=100)),
                ("description", models.CharField(max_length=240)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_amount_cents", models.IntegerField(default=0)),
                ("total_amount_cents", models.IntegerField(default=0)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="platform.invoice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("inter", "Banco Inter"), ("asaas", "Asaas")], max_length=12
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("pix", "Pix"), ("boleto", "Boleto"), ("card", "Cartão")],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("paid", "Paga"),
                            ("failed", "Falhou"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=160, unique=True)),
                ("external_id", models.CharField(blank=True, db_index=True, max_length=160)),
                ("checkout_url", models.URLField(blank=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_attempts",
                        to="platform.invoice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlanServiceRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action_code", models.CharField(max_length=100)),
                ("included_units", models.PositiveIntegerField(default=0)),
                ("overage_unit_price_cents", models.PositiveIntegerField(default=0)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_rates",
                        to="platform.plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenantUsagePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action_code", models.CharField(max_length=100)),
                (
                    "overage_mode",
                    models.CharField(
                        choices=[
                            ("block", "Bloquear no limite"),
                            ("approval", "Exigir aprovação"),
                            ("allow", "Autorizar excedente"),
                        ],
                        default="block",
                        max_length=12,
                    ),
                ),
                ("warning_percent", models.PositiveSmallIntegerField(default=80)),
                ("monthly_overage_cap_cents", models.PositiveIntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_policies",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsageMeter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action_code", models.CharField(max_length=100)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("included_units", models.PositiveIntegerField(default=0)),
                ("overage_unit_price_cents", models.PositiveIntegerField(default=0)),
                ("reserved_units", models.PositiveIntegerField(default=0)),
                ("consumed_units", models.PositiveIntegerField(default=0)),
                ("overage_units", models.PositiveIntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage_meters",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsageEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action_code", models.CharField(max_length=100)),
                ("idempotency_key", models.CharField(max_length=160, unique=True)),
                ("provider_request_id", models.CharField(blank=True, max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reservado"),
                            ("settled", "Consumido"),
                            ("released", "Liberado"),
                        ],
                        default="reserved",
                        max_length=12,
                    ),
                ),
                ("units", models.PositiveIntegerField(default=1)),
                ("overage_cents", models.PositiveIntegerField(default=0)),
                ("provider_http_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.organization"
                    ),
                ),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="platform.usagemeter",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("organization", "period_start"), name="platform_unique_invoice_competence"
            ),
        ),
        migrations.AddConstraint(
            model_name="planservicerate",
            constraint=models.UniqueConstraint(
                fields=("plan", "action_code"), name="platform_unique_plan_service_rate"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantusagepolicy",
            constraint=models.UniqueConstraint(
                fields=("organization", "action_code"), name="platform_unique_tenant_usage_policy"
            ),
        ),
        migrations.AddConstraint(
            model_name="usagemeter",
            constraint=models.UniqueConstraint(
                fields=("organization", "action_code", "period_start"),
                name="platform_unique_usage_meter_period",
            ),
        ),
    ]
