# Generated by Django 6.0.8 on 2026-09-12 13:21

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0005_central_billing"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantcontract",
            name="monthly_price_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="TenantServiceRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action_code", models.CharField(max_length=100)),
                ("included_units", models.PositiveIntegerField(default=0)),
                ("overage_unit_price_cents", models.PositiveIntegerField(default=0)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_rates",
                        to="platform.tenantcontract",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contract", "action_code"),
                        name="platform_unique_contract_service_rate",
                    )
                ],
            },
        ),
    ]
