# Generated by Django 6.0.8 on 2026-09-12 16:23

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0007_dominiosupportticket"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentWebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("inter", "Banco Inter"), ("asaas", "Asaas")], max_length=12
                    ),
                ),
                ("event_id", models.CharField(max_length=160)),
                ("event_name", models.CharField(max_length=80)),
                ("external_id", models.CharField(max_length=160)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "event_id"),
                        name="platform_unique_payment_webhook_event",
                    )
                ],
            },
        ),
    ]
