# Generated by Django 6.0.7 on 2026-09-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0010_self_service_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantcontract',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('trial', 'Teste gratuito'), ('active', 'Ativo'), ('grace', 'Carência'), ('suspended', 'Suspenso'), ('archived', 'Arquivado')], default='draft', max_length=16),
        ),
    ]
