# Generated by Django 6.0.7 on 2026-09-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0014_provider_public_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="modules",
            field=models.JSONField(default=list),
        ),
    ]
