# Generated by Django 6.0.7 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0016_clear_unverified_default_support_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformconfiguration",
            name="trial_ai_included_requests",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="signupintent",
            name="trial_ai_included_requests",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
