# Generated by Django 6.0.7 on 2026-09-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0017_platformconfiguration_trial_ai_included_requests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupintent',
            name='marketing_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signupintent',
            name='marketing_opt_in_ip_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='signupintent',
            name='marketing_opted_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signupintent',
            name='privacy_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='signupintent',
            name='terms_acceptance_ip_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='signupintent',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
