# Generated by Django 5.2.7 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0018_signup_legal_acceptance"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformconfiguration",
            name="copilot_available_for_offices",
            field=models.BooleanField(default=False),
        ),
    ]
