# Generated by Django 6.0.8 on 2026-09-14 17:54

from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0022_tenantcontract_monthly_price_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfiguration',
            name='transactional_email_from',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='transactional_email_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='transactional_email_password',
            field=apps.common.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='transactional_email_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='transactional_email_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='transactional_email_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
