# Generated by Django 6.0.8 on 2026-09-14

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("platform", "0023_platformconfiguration_transactional_email")]

    operations = [
        migrations.CreateModel(
            name="OperationalRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.CharField(
                        choices=[
                            ("advance_lifecycles", "Ciclo de testes e contratos"),
                            ("close_competence", "Fechamento de competência"),
                            ("refresh_knowledge", "Conhecimento dos escritórios"),
                            ("refresh_shared_knowledge", "Conhecimento compartilhado"),
                            ("purge_intelligence", "Retenção do Copiloto"),
                            ("retry_attachments", "Anexos pendentes"),
                            ("refresh_reform", "Radar da Reforma"),
                        ],
                        db_index=True,
                        max_length=48,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("running", "Em execução"),
                            ("succeeded", "Concluída"),
                            ("failed", "Falhou"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.JSONField(default=dict)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("error_message", models.CharField(blank=True, max_length=240)),
            ],
            options={
                "indexes": [models.Index(fields=["task", "-started_at"], name="platform_op_task_a84773_idx")],
            },
        )
    ]
