# Generated by Django 6.0.8 on 2026-09-14 19:10

from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0024_operationalrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfiguration',
            name='cloud_fallback_api_key',
            field=apps.common.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='cloud_fallback_daily_limit_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='cloud_fallback_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='cloud_fallback_max_request_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='cloud_fallback_model',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='cloud_fallback_monthly_limit_cents',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
