# Generated by Django 6.0.7 on 2026-09-15 22:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_membership_can_acknowledge_dte'),
        ('platform', '0027_replace_journey_offer_with_triage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPriceBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativa'), ('retired', 'Encerrada')], default='draft', max_length=12)),
                ('token_price_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_overage_cap_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_token_price_books', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='token_price_books', to='platform.tenantcontract')),
            ],
        ),
        migrations.CreateModel(
            name='TokenModuleRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_code', models.CharField(max_length=40)),
                ('monthly_base_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('included_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='module_rates', to='platform.tokenpricebook')),
            ],
        ),
        migrations.CreateModel(
            name='TokenMeter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_code', models.CharField(max_length=40)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('included_tokens', models.PositiveIntegerField()),
                ('token_price_cents', models.PositiveIntegerField()),
                ('reserved_tokens', models.PositiveIntegerField(default=0)),
                ('consumed_tokens', models.PositiveIntegerField(default=0)),
                ('overage_tokens', models.PositiveIntegerField(default=0)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='platform.tenantcontract')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='token_meters', to='organizations.organization')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='platform.tokenpricebook')),
            ],
        ),
        migrations.CreateModel(
            name='TokenUsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_code', models.CharField(max_length=40)),
                ('action_code', models.CharField(max_length=100)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('status', models.CharField(choices=[('reserved', 'Reservado'), ('settled', 'Consumido'), ('released', 'Liberado')], default='reserved', max_length=12)),
                ('tokens', models.PositiveIntegerField()),
                ('token_price_cents', models.PositiveIntegerField()),
                ('overage_cents', models.PositiveIntegerField(default=0)),
                ('provider_request_id', models.CharField(blank=True, max_length=160)),
                ('provider_http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='platform.tokenmeter')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TokenActionWeight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_code', models.CharField(max_length=100)),
                ('tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('module_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_weights', to='platform.tokenmodulerate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('module_rate', 'action_code'), name='platform_unique_token_action_weight'), models.CheckConstraint(condition=models.Q(('tokens__isnull', True), ('tokens__gt', 0), _connector='OR'), name='platform_token_weight_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='tokenpricebook',
            constraint=models.UniqueConstraint(fields=('contract', 'version'), name='platform_unique_token_book_version'),
        ),
        migrations.AddConstraint(
            model_name='tokenpricebook',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('contract',), name='platform_unique_active_token_book'),
        ),
        migrations.AddConstraint(
            model_name='tokenpricebook',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'active'), _negated=True), models.Q(('token_price_cents__gt', 0), ('monthly_overage_cap_cents__isnull', False)), _connector='OR'), name='platform_active_token_book_has_price_cap'),
        ),
        migrations.AddConstraint(
            model_name='tokenmodulerate',
            constraint=models.UniqueConstraint(fields=('book', 'module_code'), name='platform_unique_token_module_rate'),
        ),
        migrations.AddConstraint(
            model_name='tokenmeter',
            constraint=models.UniqueConstraint(fields=('organization', 'module_code', 'period_start'), name='platform_unique_token_meter_period'),
        ),
    ]
