# Generated by Django 6.0.7 on 2026-09-15 23:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0028_tokenpricebook_tokenmodulerate_tokenmeter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tokenpricebook',
            name='platform_active_token_book_has_price_cap',
        ),
        migrations.AddConstraint(
            model_name='tokenpricebook',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'active'), _negated=True), models.Q(('token_price_cents__gt', 0), ('monthly_overage_cap_cents__isnull', False), ('effective_from__isnull', False), ('accepted_by__isnull', False), ('accepted_at__isnull', False)), _connector='OR'), name='platform_active_token_book_has_price_cap'),
        ),
    ]
