# Generated by Django 6.0.7 on 2026-09-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0029_remove_tokenpricebook_platform_active_token_book_has_price_cap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalrun',
            name='state',
            field=models.CharField(choices=[('running', 'Em execução'), ('succeeded', 'Concluída'), ('partial', 'Parcial'), ('failed', 'Falhou')], default='running', max_length=16),
        ),
    ]
