# Generated by Django 6.0.8 on 2026-09-15 23:21

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_membership_can_acknowledge_dte'),
        ('platform', '0030_alter_operationalrun_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCloseDeferral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('reason', models.CharField(default='reserved_usage', max_length=40)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_close_deferrals', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['resolved_at', 'period_start'], name='plat_bill_deferral_open_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'period_start'), name='platform_unique_billing_close_deferral')],
            },
        ),
    ]
