# Generated by Django 6.0.8 on 2026-09-16 13:03

from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0031_billingclosedeferral'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfiguration',
            name='integra_certificate_blob',
            field=apps.common.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='integra_certificate_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='integra_certificate_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='integra_certificate_password',
            field=apps.common.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='integra_certificate_subject',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='integra_certificate_valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
