# Generated by Django 6.0.8 on 2026-09-17 12:59

import apps.common.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0032_platformconfiguration_integra_certificate_blob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfiguration',
            name='integra_autor_pedido_cnpj',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='integra_consumer_key',
            field=apps.common.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='integra_consumer_secret',
            field=apps.common.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='integra_contratante_cnpj',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='integra_environment',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
