# Generated by Django 6.0.7 on 2026-09-09 14:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_alter_membership_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientCompany",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("cnpj_masked", models.CharField(blank=True, max_length=18)),
                ("dominio_code", models.CharField(blank=True, db_index=True, max_length=64)),
                ("active", models.BooleanField(default=True)),
                ("last_dominio_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=120)),
                ("subject_name", models.CharField(blank=True, max_length=240)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("pfx_blob", apps.common.encryption.EncryptedTextField()),
                ("password", apps.common.encryption.EncryptedTextField()),
                ("fingerprint_sha256", models.CharField(db_index=True, max_length=64)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="hub.clientcompany",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccumulatorRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("match", models.JSONField(default=dict)),
                ("accumulator_code", models.CharField(max_length=80)),
                ("active", models.BooleanField(default=True)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("is_transitory", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accumulator_rules",
                        to="hub.clientcompany",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "name"),
            },
        ),
        migrations.CreateModel(
            name="AccumulatorObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("accumulator_code", models.CharField(max_length=80)),
                ("service_code", models.CharField(blank=True, max_length=60)),
                ("counterparty_ref", models.CharField(blank=True, max_length=80)),
                ("frequency", models.PositiveIntegerField(default=1)),
                ("last_used_at", models.DateTimeField(db_index=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accumulator_observations",
                        to="hub.clientcompany",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Connector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("dominio_agent", "Agente Domínio local"),
                            ("onvio", "Onvio API"),
                            ("integra", "Integra Contador"),
                        ],
                        max_length=32,
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("status", models.CharField(default="not_configured", max_length=24)),
                ("encrypted_configuration", apps.common.encryption.EncryptedTextField(blank=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=80)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsumptionConfirmation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action_code", models.CharField(max_length=100)),
                ("scope_summary", models.CharField(max_length=240)),
                ("estimated_units", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="serpro_confirmations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmations",
                        to="hub.connector",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NfseDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_nsu", models.CharField(blank=True, db_index=True, max_length=80)),
                ("document_hash", models.CharField(db_index=True, max_length=64)),
                ("original_xml", apps.common.encryption.EncryptedTextField()),
                ("normalized_data", models.JSONField(default=dict)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nfse_documents",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("-captured_at",),
            },
        ),
        migrations.CreateModel(
            name="IntegrationArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("accumulator_code", models.CharField(max_length=80)),
                ("applied_rule", models.CharField(blank=True, max_length=120)),
                ("confidence", models.PositiveSmallIntegerField(default=0)),
                ("evidence", models.JSONField(default=dict)),
                ("export_format", models.CharField(default="hub-nfse-v1", max_length=32)),
                ("payload", models.JSONField(default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="integration_artifacts",
                        to="hub.nfsedocument",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NfseSync",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checkpoint_nsu", models.CharField(blank=True, max_length=80)),
                ("status", models.CharField(default="idle", max_length=24)),
                ("last_error_code", models.CharField(blank=True, max_length=80)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hub.certificate",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nfse_syncs",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfficeProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("legal_name", models.CharField(blank=True, max_length=180)),
                (
                    "contract_status",
                    models.CharField(
                        choices=[
                            ("trial", "Em carência"),
                            ("active", "Ativo"),
                            ("suspended", "Suspenso"),
                        ],
                        default="trial",
                        max_length=16,
                    ),
                ),
                ("grace_ends_at", models.DateField(blank=True, null=True)),
                ("reference_invoice_note", models.CharField(blank=True, max_length=240)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_profile",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductModule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("nfse", "NFS-e Inteligente"),
                            ("guides", "Guias e DCTFWeb"),
                            ("integra", "Central Integra Contador"),
                            ("reconciliation", "Conciliação OFX x Domínio"),
                            ("reform", "Radar da Reforma Tributária"),
                        ],
                        max_length=32,
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("enabled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Aberta"), ("resolved", "Resolvida")],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(max_length=180)),
                ("suggested_accumulator", models.CharField(blank=True, max_length=80)),
                ("confidence", models.PositiveSmallIntegerField(default=0)),
                ("resolved_accumulator", models.CharField(blank=True, max_length=80)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_case",
                        to="hub.nfsedocument",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_nfse_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UsageAllowance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("companies", "Empresas"),
                            ("users", "Usuários"),
                            ("documents", "Documentos/mês"),
                        ],
                        max_length=24,
                    ),
                ),
                ("included", models.PositiveIntegerField(default=0)),
                ("consumed", models.PositiveIntegerField(default=0)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="clientcompany",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dominio_code__gt", "")),
                fields=("organization", "dominio_code"),
                name="hub_unique_dominio_company_code",
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["organization", "valid_until"], name="hub_certifi_organiz_9e7fcd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accumulatorobservation",
            index=models.Index(
                fields=["organization", "created_at"], name="hub_accumul_organiz_aea381_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="connector",
            constraint=models.UniqueConstraint(
                fields=("organization", "kind"), name="hub_unique_connector_per_office"
            ),
        ),
        migrations.AddIndex(
            model_name="consumptionconfirmation",
            index=models.Index(
                fields=["organization", "created_at"], name="hub_consump_organiz_269211_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="nfsedocument",
            constraint=models.UniqueConstraint(
                fields=("organization", "document_hash"), name="hub_unique_nfse_document_hash"
            ),
        ),
        migrations.AddConstraint(
            model_name="nfsesync",
            constraint=models.UniqueConstraint(
                fields=("organization", "company"), name="hub_unique_nfse_sync_company"
            ),
        ),
        migrations.AddIndex(
            model_name="officeprofile",
            index=models.Index(
                fields=["organization", "created_at"], name="hub_officep_organiz_f4b95b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productmodule",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="hub_unique_module_per_office"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewcase",
            index=models.Index(
                fields=["organization", "created_at"], name="hub_reviewc_organiz_e86bfa_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="usageallowance",
            constraint=models.UniqueConstraint(
                fields=("organization", "metric", "period_start"), name="hub_unique_usage_period"
            ),
        ),
    ]
