# Generated by Django 6.0.7 on 2026-09-09 20:21

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):
    dependencies = [("hub", "0001_initial"), ("organizations", "0002_alter_membership_role")]

    operations = [
        migrations.CreateModel(
            name="ControlPlaneBinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("remote_installation_id", models.UUIDField(unique=True)),
                ("controller_url", models.URLField()),
                ("device_private_key", apps.common.encryption.EncryptedTextField()),
                ("controller_public_key", models.CharField(max_length=120)),
                ("cached_control", models.JSONField(default=dict)),
                ("cache_expires_at", models.DateTimeField(blank=True, null=True)),
                ("applied_configuration_version", models.PositiveBigIntegerField(default=0)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_error", models.CharField(blank=True, max_length=240)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_plane_binding",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyAccessGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("modules", models.JSONField(default=list)),
                ("capabilities", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_grants",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_grants",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "membership", "is_active"],
                        name="hub_company_organiz_8a6761_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("membership", "company"), name="hub_unique_company_access_grant"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RemoteSupportGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject", models.CharField(max_length=254)),
                ("company_ids", models.JSONField(default=list)),
                ("justification", models.CharField(max_length=500)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("source_hash", models.CharField(max_length=64, unique=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "created_at"], name="hub_remotes_organiz_d4ed7b_idx"
                    )
                ]
            },
        ),
    ]
