# Generated by Django 6.0.8 on 2026-09-10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hub", "0003_dte_runs_and_messages"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("details", models.TextField(blank=True)),
                ("due_on", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[("normal", "Normal"), ("high", "Alta")],
                        default="normal",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Em aberto"), ("completed", "Concluída")],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_tasks",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_operational_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_operational_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={"ordering": ("status", "due_on", "-created_at")},
        ),
        migrations.AddIndex(
            model_name="operationaltask",
            index=models.Index(
                fields=["organization", "status", "due_on"], name="hub_operat_organiz_59d3f8_idx"
            ),
        ),
    ]
