# Generated by Django 6.0.8 on 2026-09-10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("hub", "0004_operationaltask")]

    operations = [
        migrations.RenameIndex(
            model_name="operationaltask",
            new_name="hub_operati_organiz_542757_idx",
            old_name="hub_operat_organiz_59d3f8_idx",
        )
    ]
