# Generated by Django 6.0.8 on 2026-09-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0005_rename_operational_task_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="officeprofile",
            name="require_mfa",
            field=models.BooleanField(default=False),
        ),
    ]
