# Generated by Django 6.0.8 on 2026-09-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0006_officeprofile_require_mfa"),
    ]

    operations = [
        migrations.AddField(
            model_name="officeprofile",
            name="require_dominio_code",
            field=models.BooleanField(default=False),
        ),
    ]
