# Generated by Django 6.0.8 on 2026-09-12 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0007_officeprofile_require_dominio_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumptionconfirmation",
            name="connector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="confirmations",
                to="hub.connector",
            ),
        ),
    ]
