# Generated by Django 6.0.8 on 2026-09-12 13:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0008_central_contract_pricing"),
        ("organizations", "0002_alter_membership_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalGuide",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("dctfweb", "DCTFWeb"),
                            ("das", "DAS Simples Nacional"),
                            ("mei", "DAS MEI"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Pronta para emitir"),
                            ("queued", "Na fila"),
                            ("issuing", "Emitindo"),
                            ("issued", "Emitida"),
                            ("failed", "Não emitida"),
                            ("skipped", "Dispensada"),
                        ],
                        default="ready",
                        max_length=16,
                    ),
                ),
                ("reference", models.CharField(max_length=120)),
                ("competence", models.CharField(max_length=7)),
                ("due_on", models.DateField(db_index=True)),
                ("amount_cents", models.PositiveIntegerField(default=0)),
                ("integra_service_key", models.CharField(max_length=100)),
                ("issue_attempt", models.PositiveSmallIntegerField(default=0)),
                ("provider_request_id", models.CharField(blank=True, max_length=160)),
                ("provider_payload", apps.common.encryption.EncryptedTextField(blank=True)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("error_message", models.CharField(blank=True, max_length=240)),
                ("issue_requested_at", models.DateTimeField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fiscal_guides",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "issue_requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_fiscal_guides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("due_on", "company__name", "reference"),
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "due_on"],
                        name="hub_fguide_org_stat_due_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "company", "reference"),
                        name="hub_unique_fiscal_guide_reference",
                    )
                ],
            },
        ),
    ]
