# Generated by Django 6.0.8 on 2026-09-12 14:53

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("hub", "0009_fiscal_guides")]

    operations = [
        migrations.CreateModel(
            name="ReformSourceStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("rfb", "Receita Federal"),
                            ("fazenda", "Ministério da Fazenda"),
                            ("planalto", "Planalto"),
                        ],
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("last_collected_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=240)),
                ("items_seen", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ReformAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("rfb", "Receita Federal"),
                            ("fazenda", "Ministério da Fazenda"),
                            ("planalto", "Planalto"),
                        ],
                        max_length=16,
                    ),
                ),
                ("external_key", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=360)),
                ("source_url", models.URLField(max_length=1500)),
                ("summary", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "relevance",
                    models.CharField(
                        choices=[
                            ("reform", "Reforma tributária"),
                            ("fiscal", "Fiscal"),
                            ("general", "Geral"),
                        ],
                        default="general",
                        max_length=16,
                    ),
                ),
                ("content_hash", models.CharField(max_length=64)),
            ],
            options={
                "ordering": ("-published_at", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["source", "relevance", "published_at"],
                        name="hub_reforma_source_fbc16e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "external_key"), name="hub_unique_reform_alert_source"
                    )
                ],
            },
        ),
    ]
