# Generated by Django 6.0.8 on 2026-09-12 15:57

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0011_bankstatementimport_banktransaction_and_more"),
        ("organizations", "0002_alter_membership_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="DominioBankEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_id", models.CharField(max_length=160)),
                ("occurred_on", models.DateField(db_index=True)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("amount_cents", models.BigIntegerField()),
                ("direction", models.CharField(blank=True, max_length=8)),
                ("is_linked", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dominio_bank_entries",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_on", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="ReconciliationMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("matched", "Conciliado"),
                            ("ambiguous", "Revisar"),
                            ("unmatched", "Sem correspondência"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "dominio_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciliation_matches",
                        to="hub.dominiobankentry",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliation_match",
                        to="hub.banktransaction",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="dominiobankentry",
            index=models.Index(
                fields=["organization", "company", "occurred_on"],
                name="hub_dominio_organiz_31b11c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dominiobankentry",
            index=models.Index(
                fields=["organization", "occurred_on", "amount_cents"],
                name="hub_dominio_organiz_2a6149_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="dominiobankentry",
            constraint=models.UniqueConstraint(
                fields=("organization", "source_id"), name="hub_unique_dominio_bank_entry"
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliationmatch",
            index=models.Index(
                fields=["organization", "status"], name="hub_reconci_organiz_72540a_idx"
            ),
        ),
    ]
