# Generated by Django 6.0.8 on 2026-09-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0013_reconciliationmatch_is_manual_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientJourney",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=__import__("uuid").uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Em andamento"),
                            ("paused", "Pausada"),
                            ("completed", "Concluída"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("due_on", models.DateField(blank=True, null=True)),
                ("portal_visible", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journeys",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_journeys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("due_on", "-created_at")},
        ),
        migrations.CreateModel(
            name="JourneyStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=__import__("uuid").uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("position", models.PositiveSmallIntegerField(default=1)),
                ("due_on", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("portal_visible", models.BooleanField(default=False)),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="hub.clientjourney",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={"ordering": ("position", "created_at")},
        ),
        migrations.CreateModel(
            name="PortalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=__import__("uuid").uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("details", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Aguardando cliente"),
                            ("received", "Recebida"),
                            ("resolved", "Concluída"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("due_on", models.DateField(blank=True, null=True)),
                ("portal_visible", models.BooleanField(default=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="hub.clientjourney",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={"ordering": ("due_on", "-created_at")},
        ),
        migrations.AddIndex(
            model_name="clientjourney",
            index=models.Index(
                fields=["organization", "company", "status"], name="hub_clientj_organiz_a33cc8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="journeystep",
            constraint=models.UniqueConstraint(
                fields=("journey", "position"), name="hub_unique_journey_step_position"
            ),
        ),
        migrations.AlterField(
            model_name="connector",
            name="kind",
            field=models.CharField(
                choices=[
                    ("dominio_agent", "Agente Domínio local"),
                    ("onvio", "Onvio API"),
                    ("siescon", "Siescon"),
                    ("integra", "Integra Contador"),
                ],
                max_length=32,
            ),
        ),
    ]
