# Generated by Django 6.0.7 on 2026-09-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0016_self_service_data_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodule',
            name='code',
            field=models.CharField(choices=[('nfse', 'NFS-e Inteligente'), ('guides', 'Guias e DCTFWeb'), ('integra', 'Central Integra Contador'), ('reconciliation', 'Conciliação OFX x Domínio'), ('reform', 'Radar da Reforma Tributária'), ('journey', 'Jornada e Portal'), ('ai', 'IA CICA')], max_length=32),
        ),
    ]
