# Generated by Django 6.0.7 on 2026-09-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0018_alter_productmodule_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalrequest',
            name='portal_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='portalrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Aberta'), ('received', 'Recebida'), ('resolved', 'Concluída')], default='open', max_length=16),
        ),
    ]
