# Generated by Django 6.0.7 on 2026-09-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0020_disable_legacy_portal_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodule",
            name="code",
            field=models.CharField(
                choices=[
                    ("nfse", "NFS-e Inteligente"),
                    ("guides", "Guias e DCTFWeb"),
                    ("integra", "Central Integra Contador"),
                    ("reconciliation", "Conciliação OFX x Domínio"),
                    ("reform", "Radar da Reforma Tributária"),
                    ("journey", "Jornadas"),
                    ("ai", "Copiloto CICA"),
                    ("triage", "Triagem de Arquivos"),
                ],
                max_length=32,
            ),
        ),
    ]
