# Generated by Django 6.0.8 on 2026-09-15 18:11

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.common.encryption


def seed_first_list_state(apps, schema_editor):
    Message = apps.get_model("hub", "DteMessage")
    State = apps.get_model("hub", "DteMessageState")
    states = [
        State(
            organization_id=message.organization_id,
            message_id=message.id,
            read_at=message.read_at,
            science_at=message.source_science_at,
            last_seen_at=message.first_seen_at,
        )
        for message in Message.objects.using(schema_editor.connection.alias).iterator(chunk_size=500)
    ]
    State.objects.using(schema_editor.connection.alias).bulk_create(states, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0025_dtemessage_source_science_at'),
        ('organizations', '0003_membership_can_acknowledge_dte'),
    ]

    operations = [
        migrations.CreateModel(
            name='DteMessageObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('science_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', apps.common.encryption.EncryptedTextField(blank=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='hub.dtemessage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('run_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_observations', to='hub.dterunitem')),
            ],
        ),
        migrations.CreateModel(
            name='DteMessageState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('science_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hub.dtemessageobservation')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='current_state', to='hub.dtemessage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='dtemessageobservation',
            constraint=models.UniqueConstraint(fields=('run_item', 'message'), name='hub_unique_dte_list_observation'),
        ),
        migrations.AddIndex(
            model_name='dtemessagestate',
            index=models.Index(fields=['organization', 'created_at'], name='hub_dtemess_organiz_5cbf3b_idx'),
        ),
        migrations.RunPython(seed_first_list_state, migrations.RunPython.noop),
    ]
