# Generated by Django 6.0.7 on 2026-09-15 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0026_dtemessageobservation_dtemessagestate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dterunitem',
            name='continued_from',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='continuation', to='hub.dterunitem'),
        ),
        migrations.AddField(
            model_name='dterunitem',
            name='next_page_pointer',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='dterunitem',
            name='requested_page_pointer',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
