# Generated by Django 6.0.8 on 2026-09-16 04:27

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0028_alter_fiscalguide_status"),
        ("organizations", "0004_organization_is_demo"),
        ("platform", "0031_billingclosedeferral"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DctfWebDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("declaration", "Declaração completa"),
                            ("receipt", "Recibo de transmissão"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Na fila"),
                            ("fetching", "Consultando"),
                            ("available", "Disponível"),
                            ("failed", "Não obtido"),
                            ("unknown", "Resultado a confirmar"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("competence", models.CharField(max_length=7)),
                ("service_key", models.CharField(max_length=100)),
                ("attempt", models.PositiveSmallIntegerField(default=0)),
                ("requested_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("provider_request_id", models.CharField(blank=True, max_length=160)),
                ("provider_payload", apps.common.encryption.EncryptedTextField(blank=True)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("error_message", models.CharField(blank=True, max_length=240)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dctfweb_documents",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_dctfweb_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usage_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="platform.usageevent",
                    ),
                ),
            ],
            options={
                "ordering": ("-requested_at", "company__name", "competence", "kind"),
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "requested_at"],
                        name="hub_dctfdoc_org_stat_req_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "company", "competence", "kind"),
                        name="hub_unique_dctfweb_document",
                    )
                ],
            },
        ),
    ]
