# Generated by Django 6.0.8 on 2026-09-16 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0029_dctfweb_documents"),
        ("platform", "0031_billingclosedeferral"),
    ]

    operations = [
        migrations.AddField(
            model_name="dctfwebdocument",
            name="token_usage_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="platform.tokenusageevent",
            ),
        ),
    ]
