# Generated by Django 6.0.8 on 2026-09-16 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0030_dctfweb_token_usage'),
        ('platform', '0031_billingclosedeferral'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtemessageaccess',
            name='token_usage_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='platform.tokenusageevent'),
        ),
        migrations.AddField(
            model_name='dtemessageaccess',
            name='usage_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='platform.usageevent'),
        ),
        migrations.AddField(
            model_name='dterunitem',
            name='token_usage_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='platform.tokenusageevent'),
        ),
        migrations.AddField(
            model_name='dterunitem',
            name='usage_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='platform.usageevent'),
        ),
    ]
