# Generated by Django 6.0.8 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("hub", "0032_parcelamentooperation")]

    operations = [
        migrations.AddField(model_name="nfsesync", name="enabled", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="nfsesync", name="failure_count", field=models.PositiveSmallIntegerField(default=0)),
        migrations.AddField(model_name="nfsesync", name="last_batch_count", field=models.PositiveSmallIntegerField(default=0)),
        migrations.AddField(model_name="nfsesync", name="last_error_message", field=models.CharField(blank=True, max_length=500)),
        migrations.AddField(model_name="nfsesync", name="last_success_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="nfsesync", name="lease_token", field=models.UUIDField(blank=True, editable=False, null=True)),
        migrations.AddField(model_name="nfsesync", name="lease_until", field=models.DateTimeField(blank=True, editable=False, null=True)),
        migrations.AlterField(
            model_name="nfsesync", name="status",
            field=models.CharField(
                choices=[("paused", "Pausada"), ("idle", "Aguardando"), ("running", "Sincronizando"), ("retry", "Nova tentativa agendada"), ("error", "Requer atenção")],
                default="paused", max_length=24,
            ),
        ),
        migrations.RemoveConstraint(model_name="nfsedocument", name="hub_unique_nfse_document_hash"),
        migrations.AddConstraint(
            model_name="nfsedocument",
            constraint=models.UniqueConstraint(fields=("organization", "company", "document_hash"), name="hub_unique_nfse_company_document_hash"),
        ),
        migrations.AddConstraint(
            model_name="nfsedocument",
            constraint=models.UniqueConstraint(condition=models.Q(source_nsu__gt=""), fields=("organization", "company", "source_nsu"), name="hub_unique_nfse_company_source_nsu"),
        ),
    ]
