# Generated by Django 6.0.8 on 2026-09-17 12:26

import apps.hub.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0033_nfse_operational_sync"),
        ("organizations", "0004_organization_is_demo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("bank_code", models.CharField(blank=True, max_length=20)),
                ("account_reference", models.CharField(blank=True, max_length=160)),
                ("ledger_code", models.CharField(blank=True, max_length=64)),
                ("active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_accounts",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occurred_on", models.DateField()),
                ("history", models.CharField(max_length=500)),
                ("purpose", models.CharField(max_length=24)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("approved", "Aprovado"),
                            ("exported", "Exportado"),
                            ("invalid", "Inválido"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entries",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JournalLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_code", models.CharField(max_length=64)),
                (
                    "side",
                    models.CharField(
                        choices=[("debit", "Débito"), ("credit", "Crédito")], max_length=8
                    ),
                ),
                ("amount_cents", models.PositiveBigIntegerField()),
                ("cost_center_code", models.CharField(blank=True, max_length=64)),
                ("history", models.CharField(blank=True, max_length=500)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="hub.journalentry",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LedgerAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=200)),
                ("nature", models.CharField(blank=True, max_length=12)),
                ("active", models.BooleanField(default=True)),
                ("accepts_entries", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_accounts",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NormalizedMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_key", models.CharField(max_length=255)),
                ("source_reference", models.JSONField(default=dict)),
                ("original_date", models.CharField(blank=True, max_length=64)),
                ("occurred_on", models.DateField(blank=True, db_index=True, null=True)),
                ("original_amount", models.CharField(blank=True, max_length=64)),
                ("amount_cents", models.BigIntegerField(default=0)),
                ("currency", models.CharField(default="BRL", max_length=3)),
                (
                    "direction",
                    models.CharField(
                        choices=[("inflow", "Entrada"), ("outflow", "Saída")], max_length=12
                    ),
                ),
                ("original_description", models.CharField(blank=True, max_length=1000)),
                ("description", models.CharField(blank=True, max_length=1000)),
                ("document_number", models.CharField(blank=True, max_length=160)),
                ("counterparty", models.CharField(blank=True, max_length=255)),
                ("debit_account_code", models.CharField(blank=True, max_length=64)),
                ("credit_account_code", models.CharField(blank=True, max_length=64)),
                ("cost_center_code", models.CharField(blank=True, max_length=64)),
                ("accounting_history", models.CharField(blank=True, max_length=500)),
                (
                    "review_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("ready", "Pronto"),
                            ("ignored", "Ignorado"),
                            ("conflict", "Conflito"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "classification_source",
                    models.CharField(
                        choices=[
                            ("none", "Sem classificação"),
                            ("rule", "Regra"),
                            ("suggestion", "Sugestão"),
                            ("manual", "Manual"),
                        ],
                        default="none",
                        max_length=12,
                    ),
                ),
                ("confidence", models.PositiveSmallIntegerField(default=0)),
                ("confidence_details", models.JSONField(default=dict)),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="normalized_movements",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edited_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "financial_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="hub.financialaccount",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_on", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="MovementReconciliation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_cents", models.PositiveBigIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("suggested", "Sugerida"),
                            ("confirmed", "Confirmada"),
                            ("undone", "Desfeita"),
                        ],
                        default="suggested",
                        max_length=12,
                    ),
                ),
                ("evidence", models.JSONField(default=dict)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_movement_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movement_reconciliations",
                        to="hub.journalentry",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliations",
                        to="hub.normalizedmovement",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="journalentry",
            name="movement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journal_entries",
                to="hub.normalizedmovement",
            ),
        ),
        migrations.CreateModel(
            name="ReconciliationLayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("ofx", "OFX"), ("csv", "CSV"), ("xlsx", "XLSX"), ("pdf", "PDF")],
                        max_length=12,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("version", models.PositiveIntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
                ("header_signature", models.CharField(blank=True, max_length=64)),
                ("configuration", models.JSONField(default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliation_layouts",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciliation_layouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("company_id", "kind", "name", "-version"),
            },
        ),
        migrations.CreateModel(
            name="ReconciliationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("active", "Ativa"),
                            ("disabled", "Desativada"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("all_conditions", models.JSONField(default=list)),
                ("any_conditions", models.JSONField(default=list)),
                ("actions", models.JSONField(default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliation_rules",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciliation_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "created_at", "id"),
            },
        ),
        migrations.AddField(
            model_name="normalizedmovement",
            name="applied_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applied_movements",
                to="hub.reconciliationrule",
            ),
        ),
        migrations.CreateModel(
            name="ReconciliationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("waiting", "Aguardando"),
                            ("processing", "Processando"),
                            ("review", "Aguardando revisão"),
                            ("completed", "Concluída"),
                            ("completed_alerts", "Concluída com alertas"),
                            ("failed", "Falhou"),
                            ("canceled", "Cancelada"),
                        ],
                        default="waiting",
                        max_length=24,
                    ),
                ),
                ("stage", models.CharField(default="queued", max_length=48)),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("processed_count", models.PositiveIntegerField(default=0)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("ignored_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("checkpoint", models.JSONField(default=dict)),
                ("errors", models.JSONField(default=list)),
                ("lease_token", models.UUIDField(blank=True, editable=False, null=True)),
                ("lease_until", models.DateTimeField(blank=True, editable=False, null=True)),
                ("cancel_requested_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "continued_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retries",
                        to="hub.reconciliationrun",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciliation_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "layout_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="hub.reconciliationlayout",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="normalizedmovement",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="hub.reconciliationrun",
            ),
        ),
        migrations.CreateModel(
            name="ReconciliationSourceFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("ofx", "OFX"), ("csv", "CSV"), ("xlsx", "XLSX"), ("pdf", "PDF")],
                        max_length=12,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("bank_statement", "Extrato bancário"),
                            ("accounting", "Registros contábeis"),
                            ("obligation", "Títulos ou obrigações"),
                            ("document", "Documento comprobatório"),
                        ],
                        max_length=20,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("content_hash", models.CharField(max_length=64)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("size_bytes", models.PositiveIntegerField()),
                (
                    "content",
                    models.FileField(upload_to=apps.hub.models.private_reconciliation_path),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliation_files",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciliation_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="reconciliationrun",
            name="source_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="hub.reconciliationsourcefile",
            ),
        ),
        migrations.AddField(
            model_name="normalizedmovement",
            name="source_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="hub.reconciliationsourcefile",
            ),
        ),
        migrations.CreateModel(
            name="AccountingExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("generating", "Gerando"),
                            ("ready", "Arquivo gerado"),
                            ("confirmed", "Importação confirmada"),
                            ("failed", "Falhou"),
                        ],
                        default="generating",
                        max_length=16,
                    ),
                ),
                (
                    "adapter_version",
                    models.CharField(default="dominio-3.1-pending-homologation", max_length=32),
                ),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                (
                    "content",
                    models.FileField(
                        blank=True, upload_to=apps.hub.models.private_reconciliation_path
                    ),
                ),
                ("entry_ids", models.JSONField(default=list)),
                ("reexport_reason", models.CharField(blank=True, max_length=240)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounting_exports",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_accounting_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounting_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "reexport_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reexports",
                        to="hub.accountingexport",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["organization", "company", "period_start", "period_end"],
                        name="hub_account_organiz_ad2b3f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AccountingPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("lock_reason", models.CharField(blank=True, max_length=240)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounting_periods",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_accounting_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "company", "starts_on", "ends_on"),
                        name="hub_unique_accounting_period",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=160)),
                ("active", models.BooleanField(default=True)),
                ("required", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_centers",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "company", "code"),
                        name="hub_unique_cost_center_code",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="financialaccount",
            constraint=models.UniqueConstraint(
                fields=("organization", "company", "account_reference"),
                name="hub_unique_financial_account_reference",
            ),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(
                fields=["organization", "created_at"], name="hub_journal_organiz_2e0b30_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgeraccount",
            constraint=models.UniqueConstraint(
                fields=("organization", "company", "code"), name="hub_unique_ledger_account_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="movementreconciliation",
            constraint=models.UniqueConstraint(
                fields=("movement", "entry"), name="hub_unique_movement_entry_reconciliation"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["organization", "company", "occurred_on", "state"],
                name="hub_journal_organiz_132f7f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="reconciliationlayout",
            constraint=models.UniqueConstraint(
                fields=("organization", "company", "kind", "name", "version"),
                name="hub_unique_reconciliation_layout_version",
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliationrule",
            index=models.Index(
                fields=["organization", "company", "state", "priority"],
                name="hub_reconci_organiz_f76366_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliationsourcefile",
            index=models.Index(
                fields=["organization", "company", "created_at"],
                name="hub_reconci_organiz_e0082d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="reconciliationsourcefile",
            constraint=models.UniqueConstraint(
                fields=("organization", "company", "content_hash"),
                name="hub_unique_reconciliation_file_hash",
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliationrun",
            index=models.Index(
                fields=["organization", "state", "created_at"],
                name="hub_reconci_organiz_ef1a53_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliationrun",
            index=models.Index(fields=["lease_until"], name="hub_reconci_lease_u_ff181b_idx"),
        ),
        migrations.AddIndex(
            model_name="normalizedmovement",
            index=models.Index(
                fields=["organization", "company", "occurred_on"],
                name="hub_normali_organiz_d1487e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="normalizedmovement",
            index=models.Index(
                fields=["organization", "company", "review_state"],
                name="hub_normali_organiz_57967e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="normalizedmovement",
            constraint=models.UniqueConstraint(
                fields=("source_file", "source_key"), name="hub_unique_normalized_source_key"
            ),
        ),
    ]
