# Generated by Django 6.0.8 on 2026-09-17 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0034_reconciliation_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationsourcefile',
            name='financial_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_files', to='hub.financialaccount'),
        ),
    ]
