# Generated by Django 6.0.8 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0035_reconciliation_source_financial_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="reconciliationrun",
            name="updated_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
