# Generated by Django 6.0.8 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0036_reconciliationrun_updated_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="source_movement_revision",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
