# Generated by Django 6.0.8 on 2026-09-23 12:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0039_onboarding_progress'),
        ('organizations', '0004_organization_is_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=180)),
                ('area', models.CharField(choices=[('accounting', 'Contábil'), ('fiscal', 'Fiscal'), ('payroll', 'Folha'), ('general', 'Geral')], max_length=16)),
                ('description', models.TextField(blank=True)),
                ('evidence_requirement', models.CharField(choices=[('source_or_human', 'Fonte ou confirmação humana'), ('source', 'Fonte integrada'), ('human', 'Confirmação humana')], default='source_or_human', max_length=24)),
                ('version', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ('area', 'code', '-version'),
            },
        ),
        migrations.CreateModel(
            name='OperationalActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_version', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=180)),
                ('area', models.CharField(choices=[('accounting', 'Contábil'), ('fiscal', 'Fiscal'), ('payroll', 'Folha'), ('general', 'Geral')], max_length=16)),
                ('competence', models.DateField(blank=True, db_index=True, null=True)),
                ('legal_due_on', models.DateField(blank=True, db_index=True, null=True)),
                ('internal_due_on', models.DateField(blank=True, db_index=True, null=True)),
                ('work_status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('blocked', 'Impedida'), ('completed', 'Concluída'), ('waived', 'Dispensada')], default='pending', max_length=16)),
                ('processing_status', models.CharField(choices=[('not_verified', 'Não verificado'), ('open', 'Aberto'), ('processed', 'Processado'), ('closed', 'Fechado'), ('reopened', 'Reaberto')], default='not_verified', max_length=16)),
                ('obligation_status', models.CharField(choices=[('not_applicable', 'Não aplicável'), ('not_prepared', 'Não preparada'), ('prepared', 'Preparada'), ('submitted', 'Transmitida'), ('accepted', 'Aceita'), ('rejected', 'Rejeitada'), ('unknown', 'Resultado a confirmar')], default='not_applicable', max_length=20)),
                ('payment_status', models.CharField(choices=[('not_applicable', 'Não aplicável'), ('expected', 'Previsto'), ('guide_available', 'Guia disponível'), ('informed', 'Pagamento informado'), ('confirmed', 'Pagamento comprovado')], default='not_applicable', max_length=20)),
                ('freshness', models.CharField(choices=[('current', 'Atualizado'), ('stale', 'Desatualizado'), ('unavailable', 'Fonte indisponível'), ('not_configured', 'Integração não configurada')], default='not_configured', max_length=20)),
                ('requires_accepted_obligation', models.BooleanField(default=False)),
                ('evidence_requirement', models.CharField(choices=[('source_or_human', 'Fonte ou confirmação humana'), ('source', 'Fonte integrada'), ('human', 'Confirmação humana')], default='source_or_human', max_length=24)),
                ('blocked_reason', models.CharField(blank=True, max_length=500)),
                ('waived_reason', models.CharField(blank=True, max_length=500)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_operational_activities', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='hub.clientcompany')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_operational_activities', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='hub.activitytemplate')),
            ],
            options={
                'ordering': ('internal_due_on', 'legal_due_on', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='OperationalActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=48)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='hub.operationalactivity')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ('-occurred_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='OperationalEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('source', 'Fonte integrada'), ('document', 'Documento'), ('human', 'Confirmação humana'), ('official', 'Retorno oficial')], max_length=16)),
                ('reference', models.CharField(blank=True, max_length=180)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_items', to='hub.operationalactivity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-observed_at', '-created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='activitytemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'code', 'version'), name='hub_unique_activity_template_version'),
        ),
        migrations.AddIndex(
            model_name='operationalactivity',
            index=models.Index(fields=['organization', 'assigned_to', 'work_status', 'internal_due_on'], name='hub_operati_organiz_9012e7_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalactivity',
            index=models.Index(fields=['organization', 'company', 'competence'], name='hub_operati_organiz_579181_idx'),
        ),
        migrations.AddConstraint(
            model_name='operationalactivity',
            constraint=models.UniqueConstraint(fields=('organization', 'company', 'code', 'competence', 'template_version'), name='hub_unique_operational_activity_competence'),
        ),
        migrations.AddIndex(
            model_name='operationalactivityevent',
            index=models.Index(fields=['organization', 'activity', 'occurred_at'], name='hub_operati_organiz_ba69c9_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalevidence',
            index=models.Index(fields=['organization', 'activity', 'kind'], name='hub_operati_organiz_00e171_idx'),
        ),
    ]
