# Generated by Django 6.0.8 on 2026-09-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0039_onboarding_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodule',
            name='code',
            field=models.CharField(choices=[('nfse', 'NFS-e Inteligente'), ('guides', 'Guias e DCTFWeb'), ('integra', 'Central Integra Contador'), ('reconciliation', 'Conciliação OFX x Domínio'), ('reform', 'Radar da Reforma Tributária'), ('journey', 'Jornadas'), ('ai', 'Copiloto CICA'), ('triage', 'Triagem de Arquivos'), ('profitability', 'Rentabilidade por Cliente')], max_length=32),
        ),
    ]
