# Generated by Django 6.0.8 on 2026-09-23 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0040_central_operacional'),
        ('organizations', '0004_organization_is_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='operationalactivity',
            constraint=models.UniqueConstraint(condition=models.Q(('competence__isnull', True)), fields=('organization', 'company', 'code', 'template_version'), name='hub_unique_operational_activity_without_competence'),
        ),
    ]
