# Generated by Django 6.0.8 on 2026-09-23 13:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0041_operationalactivity_hub_unique_operational_activity_without_competence'),
        ('organizations', '0004_organization_is_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytemplate',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Mensal'), ('ad_hoc', 'Sob demanda')], default='monthly', max_length=16),
        ),
        migrations.AddField(
            model_name='activitytemplate',
            name='internal_due_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitytemplate',
            name='legal_due_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitytemplate',
            name='requires_accepted_obligation',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ActivityTemplateAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_due_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('internal_due_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_template_assignments', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_template_assignments', to='hub.clientcompany')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_assignments', to='hub.activitytemplate')),
            ],
            options={
                'ordering': ('template__area', 'template__code', 'company__name'),
                'constraints': [models.UniqueConstraint(fields=('organization', 'template', 'company'), name='hub_unique_activity_template_company_assignment')],
            },
        ),
    ]
