# Generated by Django 6.0.8 on 2026-09-23 13:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0042_activitytemplate_frequency_and_more'),
        ('organizations', '0004_organization_is_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalSourceObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('successful', models.BooleanField()),
                ('external_reference', models.CharField(blank=True, max_length=180)),
                ('source_version', models.CharField(blank=True, max_length=120)),
                ('processing_status', models.CharField(blank=True, choices=[('not_verified', 'Não verificado'), ('open', 'Aberto'), ('processed', 'Processado'), ('closed', 'Fechado'), ('reopened', 'Reaberto')], max_length=16)),
                ('obligation_status', models.CharField(blank=True, choices=[('not_applicable', 'Não aplicável'), ('not_prepared', 'Não preparada'), ('prepared', 'Preparada'), ('submitted', 'Transmitida'), ('accepted', 'Aceita'), ('rejected', 'Rejeitada'), ('unknown', 'Resultado a confirmar')], max_length=20)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_observations', to='hub.operationalactivity')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operational_observations', to='hub.datasource')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ('-observed_at', '-created_at'),
                'indexes': [models.Index(fields=['organization', 'activity', 'successful', 'observed_at'], name='hub_operati_organiz_dcfbf7_idx'), models.Index(fields=['organization', 'data_source', 'observed_at'], name='hub_operati_organiz_687772_idx')],
            },
        ),
    ]
