# Generated by Django 6.0.8 on 2026-09-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0043_operational_source_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytemplate',
            name='requires_processing_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operationalactivity',
            name='requires_processing_closed',
            field=models.BooleanField(default=False),
        ),
    ]
