# Generated by Django 6.0.8 on 2026-09-23 14:02

from django.core.exceptions import ValidationError
from django.db import migrations, models


def populate_commercial_roots(apps, schema_editor):
    from apps.common.cnpj import normalize_cnpj

    ClientCompany = apps.get_model("hub", "ClientCompany")
    for company in ClientCompany.objects.exclude(cnpj_masked="").iterator():
        try:
            root = normalize_cnpj(company.cnpj_masked)[:8]
        except ValidationError:
            continue
        ClientCompany.objects.filter(pk=company.pk).update(commercial_root_cnpj=root)


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0044_activity_processing_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcompany',
            name='commercial_root_cnpj',
            field=models.CharField(blank=True, db_index=True, max_length=8),
        ),
        migrations.RunPython(populate_commercial_roots, migrations.RunPython.noop),
    ]
