# Generated by Django 6.0.8 on 2026-09-23 14:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0045_company_commercial_root'),
        ('organizations', '0004_organization_is_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriodSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competence', models.DateField(db_index=True)),
                ('source_kind', models.CharField(choices=[('erp', 'ERP'), ('document', 'Documento informado'), ('official', 'Retorno oficial'), ('manual', 'Confirmação humana')], max_length=16)),
                ('source_reference', models.CharField(max_length=240)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('workforce_count', models.PositiveIntegerField(blank=True, null=True)),
                ('gross_pay_cents', models.BigIntegerField(blank=True, null=True)),
                ('deductions_cents', models.BigIntegerField(blank=True, null=True)),
                ('employer_charges_cents', models.BigIntegerField(blank=True, null=True)),
                ('net_pay_cents', models.BigIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_snapshots', to='hub.clientcompany')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_snapshots', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_snapshots', to='hub.datasource')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ('-competence', '-observed_at'),
                'indexes': [models.Index(fields=['organization', 'company', 'competence'], name='hub_payroll_organiz_125d2f_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'company', 'competence', 'source_kind', 'source_reference'), name='hub_unique_payroll_snapshot_source_reference')],
            },
        ),
    ]
