# Generated by Django 6.0.8 on 2026-09-23 15:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0046_payroll_period_snapshots'),
        ('organizations', '0004_organization_is_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingBalanceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competence', models.DateField(db_index=True)),
                ('source_kind', models.CharField(choices=[('erp', 'ERP'), ('import', 'Importação conferida'), ('document', 'Documento informado'), ('manual', 'Confirmação humana')], max_length=16)),
                ('source_reference', models.CharField(max_length=240)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_balance_snapshots', to='hub.clientcompany')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accounting_balance_snapshots', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ('-competence', '-observed_at'),
            },
        ),
        migrations.CreateModel(
            name='AccountingBalanceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=80)),
                ('account_name', models.CharField(blank=True, max_length=240)),
                ('balance_cents', models.BigIntegerField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='hub.accountingbalancesnapshot')),
            ],
            options={
                'ordering': ('account_code',),
            },
        ),
        migrations.CreateModel(
            name='CashScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=160)),
                ('view', models.CharField(choices=[('simulation', 'Simulação'), ('projection', 'Projeção'), ('realized', 'Realizado')], max_length=16)),
                ('reference_date', models.DateField()),
                ('opening_balance_cents', models.BigIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_scenarios', to='hub.clientcompany')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cash_scenarios', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ('-reference_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CashScenarioMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_on', models.DateField(db_index=True)),
                ('description', models.CharField(max_length=240)),
                ('gross_receipt_cents', models.BigIntegerField(default=0)),
                ('payment_cents', models.BigIntegerField(default=0)),
                ('retention_cents', models.BigIntegerField(default=0)),
                ('provision_cents', models.BigIntegerField(default=0)),
                ('retention_already_provisioned', models.BooleanField(default=False)),
                ('source_reference', models.CharField(blank=True, max_length=240)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='hub.cashscenario')),
            ],
            options={
                'ordering': ('occurred_on', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DreMappingSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dre_mapping_sets', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.CreateModel(
            name='DreAccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=80)),
                ('group', models.CharField(max_length=160)),
                ('sign', models.SmallIntegerField()),
                ('mapping_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mappings', to='hub.dremappingset')),
            ],
            options={
                'ordering': ('account_code',),
            },
        ),
        migrations.AddIndex(
            model_name='accountingbalancesnapshot',
            index=models.Index(fields=['organization', 'company', 'competence'], name='hub_account_organiz_887d49_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountingbalancesnapshot',
            constraint=models.UniqueConstraint(fields=('organization', 'company', 'competence', 'source_kind', 'source_reference'), name='hub_unique_accounting_balance_snapshot_source'),
        ),
        migrations.AddConstraint(
            model_name='accountingbalanceline',
            constraint=models.UniqueConstraint(fields=('snapshot', 'account_code'), name='hub_unique_accounting_balance_line_account'),
        ),
        migrations.AddIndex(
            model_name='cashscenario',
            index=models.Index(fields=['organization', 'company', 'view', 'reference_date'], name='hub_cashsce_organiz_12ba70_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashscenariomovement',
            constraint=models.CheckConstraint(condition=models.Q(('gross_receipt_cents__gte', 0), ('payment_cents__gte', 0), ('retention_cents__gte', 0), ('provision_cents__gte', 0)), name='hub_cash_movement_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='dremappingset',
            constraint=models.UniqueConstraint(fields=('organization', 'version'), name='hub_unique_dre_mapping_set_version'),
        ),
        migrations.AddConstraint(
            model_name='dreaccountmapping',
            constraint=models.UniqueConstraint(fields=('mapping_set', 'account_code'), name='hub_unique_dre_mapping_account'),
        ),
        migrations.AddConstraint(
            model_name='dreaccountmapping',
            constraint=models.CheckConstraint(condition=models.Q(('sign__in', (-1, 1))), name='hub_dre_mapping_sign_is_valid'),
        ),
    ]
