# Generated by Django 6.0.8 on 2026-09-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0047_financial_snapshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='kind',
            field=models.CharField(choices=[('companies', 'Empresas'), ('obligations', 'Obrigações e guias'), ('accounting', 'Lançamentos contábeis'), ('accounting_balances', 'Saldos para DRE'), ('cash_scenario', 'Cenario de caixa'), ('fiscal_xml', 'Documentos fiscais XML'), ('bank_ofx', 'Extratos bancários OFX'), ('dominio_backup', 'Backup completo Domínio Web')], max_length=24),
        ),
    ]
