# Generated by Django 6.0.8 on 2026-09-23 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0049_dre_mapping_import'),
        ('organizations', '0004_organization_is_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccumulatorCatalogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accumulator_code', models.CharField(max_length=80)),
                ('name', models.CharField(blank=True, max_length=180)),
                ('active', models.BooleanField(default=True)),
                ('source_identifier', models.CharField(blank=True, max_length=160)),
                ('source_snapshot_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accumulator_catalog_entries', to='hub.clientcompany')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hub.datasource')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('source_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hub.importbatch')),
            ],
            options={
                'ordering': ('company_id', 'accumulator_code'),
                'constraints': [models.UniqueConstraint(fields=('source_batch', 'company', 'accumulator_code'), name='hub_unique_backup_accumulator_catalog_entry')],
            },
        ),
    ]
