# Generated by Django 6.0.8 on 2026-09-23 16:43

import apps.hub.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0050_dominio_web_accumulator_catalog'),
        ('organizations', '0004_organization_is_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NfseExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('ready', 'Arquivo gerado'), ('downloaded', 'Arquivo baixado'), ('import_confirmed', 'Importação confirmada')], default='ready', max_length=24)),
                ('target', models.CharField(default='dominio_xml_routine_pending_homologation', max_length=48)),
                ('adapter_version', models.CharField(default='nfse-xml-v1', max_length=48)),
                ('content_hash', models.CharField(max_length=64)),
                ('document_count', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('content', models.FileField(upload_to=apps.hub.models.private_nfse_export_path)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_nfse_exports', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfse_exports', to=settings.AUTH_USER_MODEL)),
                ('downloaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloaded_nfse_exports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'state', 'created_at'], name='hub_nfseexp_organiz_826a38_idx')],
            },
        ),
    ]
