# Generated by Django 6.0.8 on 2026-09-23 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0051_nfse_export_packages'),
        ('organizations', '0004_organization_is_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccumulatorHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accumulator_code', models.CharField(max_length=80)),
                ('name', models.CharField(blank=True, max_length=180)),
                ('source', models.CharField(choices=[('backup', 'Fotografia do Dominio Web'), ('manual', 'Cadastro manual'), ('human_review', 'Decisao humana')], max_length=16)),
                ('source_reference', models.CharField(max_length=80)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('metadata', models.JSONField(default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accumulator_history_entries', to='hub.clientcompany')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accumulator_history_entries', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ('-occurred_at', '-created_at'),
                'constraints': [models.UniqueConstraint(fields=('organization', 'source', 'source_reference'), name='hub_unique_accumulator_history_source_reference')],
            },
        ),
    ]
