# Generated by Django 6.0.8 on 2026-09-23 18:56

import apps.common.encryption
import apps.hub.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0052_accumulator_history_entries'),
        ('organizations', '0004_organization_is_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReportExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.CharField(choices=[('dre', 'DRE'), ('cash', 'Caixa')], max_length=12)),
                ('source_id', models.UUIDField()),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'XLSX')], max_length=8)),
                ('filename_stem', models.CharField(max_length=180)),
                ('snapshot', apps.common.encryption.EncryptedTextField()),
                ('snapshot_sha256', models.CharField(db_index=True, max_length=64)),
                ('state', models.CharField(choices=[('waiting', 'Aguardando'), ('rendering', 'Gerando'), ('ready', 'Disponivel'), ('failed', 'Falhou')], default='waiting', max_length=16)),
                ('content', models.FileField(blank=True, upload_to=apps.hub.models.private_financial_report_path)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('output_sha256', models.CharField(blank=True, max_length=64)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('lease_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('lease_until', models.DateTimeField(blank=True, editable=False, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_report_exports', to='hub.clientcompany')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_report_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'company', 'created_at'], name='hub_financi_organiz_a4a608_idx'), models.Index(fields=['organization', 'state', 'created_at'], name='hub_financi_organiz_b7cabf_idx'), models.Index(fields=['lease_until'], name='hub_financi_lease_u_aecc07_idx')],
            },
        ),
    ]
