# Generated by Django 6.0.8 on 2026-09-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0053_financial_report_exports"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitytemplateassignment",
            name="next_generation_competence",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
