# Generated by Django 6.0.8 on 2026-09-24 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0054_activity_recurrence_cursor'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalactivity',
            name='source_nfse_review',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_activity', to='hub.reviewcase'),
        ),
    ]
