# Generated by Django 6.0.8 on 2026-09-24 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0055_operationalactivity_source_nfse_review'),
        ('triage', '0010_alter_triageevent_from_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalactivity',
            name='source_triage_item',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_activity', to='triage.triageitem'),
        ),
    ]
