# Generated by Django 6.0.8 on 2026-09-24 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0056_operationalactivity_source_triage_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalactivity',
            name='source_reconciliation_file',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_activity', to='hub.reconciliationsourcefile'),
        ),
    ]
