# Generated by Django 6.0.8 on 2026-09-24 13:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0057_operationalactivity_source_reconciliation_file'),
        ('organizations', '0004_organization_is_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('suggested', 'Sugerida'), ('confirmed', 'Confirmada'), ('undone', 'Desfeita')], max_length=12)),
                ('amount_cents', models.PositiveBigIntegerField()),
                ('evidence', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(null=True)),
                ('is_legacy_snapshot', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='hub.movementreconciliation')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['organization', 'created_at'], name='hub_reconci_organiz_338dae_idx')],
            },
        ),
    ]
