# Generated by Django 6.0.8 on 2026-09-24 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0059_alter_importbatch_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalactivity',
            name='source_payroll_snapshot',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_activities', to='hub.payrollperiodsnapshot'),
        ),
    ]
