# Generated by Django 6.0.8 on 2026-09-24 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0060_operationalactivity_source_payroll_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalactivity',
            name='source_dte_message',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analysis_activity', to='hub.dtemessage'),
        ),
    ]
