# Generated by Django 6.0.8 on 2026-09-24 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0061_operationalactivity_source_dte_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalactivity',
            name='reform_version',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='operationalactivity',
            name='source_reform_alert',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analysis_activities', to='hub.reformalert'),
        ),
        migrations.AddField(
            model_name='operationalevidence',
            name='source_url',
            field=models.URLField(blank=True, max_length=1500),
        ),
    ]
