# Generated by Django 6.0.8 on 2026-09-24 15:08

from django.db import migrations, models


def quarantine_legacy_results(apps, schema_editor):
    apps.get_model("hub", "FiscalGuide").objects.using(
        schema_editor.connection.alias
    ).filter(status="failed", error_code="integration").update(status="unknown")


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0062_operationalactivity_reform_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalguide',
            name='status',
            field=models.CharField(choices=[('discovered', 'Apuração a conferir'), ('ready', 'Pronta para emitir'), ('queued', 'Na fila'), ('issuing', 'Emitindo'), ('issued', 'Emitida'), ('unknown', 'Resultado a confirmar'), ('failed', 'Não emitida'), ('skipped', 'Dispensada')], default='ready', max_length=16),
        ),
        migrations.RunPython(quarantine_legacy_results, migrations.RunPython.noop),
    ]
