# Generated by Django 6.0.8 on 2026-09-24 15:22

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0063_alter_fiscalguide_status'),
        ('organizations', '0004_organization_is_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalGuideAttemptEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('discovered', 'Apuração a conferir'), ('ready', 'Pronta para emitir'), ('queued', 'Na fila'), ('issuing', 'Emitindo'), ('issued', 'Emitida'), ('unknown', 'Resultado a confirmar'), ('failed', 'Não emitida'), ('skipped', 'Dispensada')], max_length=16)),
                ('request_snapshot', models.JSONField(default=dict)),
                ('requested_by_reference', models.CharField(blank=True, max_length=36)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consumption_reference', models.CharField(max_length=100)),
                ('provider_request_id', models.CharField(blank=True, max_length=160)),
                ('provider_payload', apps.common.encryption.EncryptedTextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.CharField(blank=True, max_length=240)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_events', to='hub.fiscalguide')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ('attempt', 'observed_at', 'created_at'),
                'constraints': [models.UniqueConstraint(fields=('guide', 'attempt', 'status'), name='hub_unique_guide_attempt_state')],
            },
        ),
    ]
