# Generated by Django 6.0.8 on 2026-09-24 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0064_fiscalguideattemptevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalactivity',
            name='source_dctfweb_document',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_activity', to='hub.dctfwebdocument'),
        ),
        migrations.AddField(
            model_name='operationalactivity',
            name='source_fiscal_guide',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_activity', to='hub.fiscalguide'),
        ),
        migrations.AddField(
            model_name='operationalactivity',
            name='source_parcelamento_operation',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_activity', to='hub.parcelamentooperation'),
        ),
    ]
