# Generated by Django 6.0.8 on 2026-10-05 21:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0069_accumulatorobservation_direction'),
        ('organizations', '0005_internal_test_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfseDocumentSide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(db_index=True, max_length=16)),
                ('counterparty_ref', models.CharField(blank=True, max_length=80)),
                ('counterparty_name', models.CharField(blank=True, max_length=160)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='side', to='hub.nfsedocument')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'direction'], name='hub_nfsedoc_organiz_335ea8_idx')],
            },
        ),
    ]
