# Generated by Django 6.0.8 on 2026-10-06 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fiscal_calendar", "0001_initial"),
        ("hub", "0070_nfsedocumentside"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitytemplate",
            name="due_month_offset",
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name="activitytemplate",
            name="internal_lead_business_days",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activitytemplate",
            name="legal_rule_code",
            field=models.CharField(blank=True, db_default="", default="", max_length=64),
        ),
        migrations.AddField(
            model_name="operationalactivity",
            name="legal_due_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="fiscal_calendar.taxdeadlinerule",
            ),
        ),
    ]
