# Generated by Django 6.0.8 on 2026-10-06 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0071_activitytemplate_due_month_offset_and_more"),
        ("organizations", "0006_membership_role_labels_pt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcompany",
            name="contact_email",
            field=models.EmailField(blank=True, db_default="", default="", max_length=254),
        ),
        migrations.AddField(
            model_name="clientcompany",
            name="contact_name",
            field=models.CharField(blank=True, db_default="", default="", max_length=120),
        ),
        migrations.AddField(
            model_name="clientcompany",
            name="contact_phone",
            field=models.CharField(blank=True, db_default="", default="", max_length=30),
        ),
        migrations.AddField(
            model_name="clientcompany",
            name="municipal_registration",
            field=models.CharField(blank=True, db_default="", default="", max_length=30),
        ),
        migrations.AddField(
            model_name="clientcompany",
            name="state_registration",
            field=models.CharField(blank=True, db_default="", default="", max_length=30),
        ),
        migrations.AddField(
            model_name="clientcompany",
            name="tax_regime",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mei", "MEI"),
                    ("simples", "Simples Nacional"),
                    ("presumido", "Lucro Presumido"),
                    ("real", "Lucro Real"),
                    ("imune_isenta", "Imune ou isenta"),
                    ("outro", "Outro"),
                ],
                db_default="",
                default="",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="CompanyAreaResponsible",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("accounting", "Contábil"),
                            ("fiscal", "Fiscal"),
                            ("payroll", "Folha"),
                            ("general", "Geral"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_responsibles",
                        to="hub.clientcompany",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("company__name", "area"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "area"), name="hub_unique_company_area_responsible"
                    )
                ],
            },
        ),
    ]
