# Generated by Django 6.0.8 on 2026-10-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0073_notification'),
        ('organizations', '0006_membership_role_labels_pt'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfsedocumentside',
            name='access_key',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='nfsedocumentside',
            name='competence',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfsedocumentside',
            name='counterparty_document',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='nfsedocumentside',
            name='crf_retained',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='nfsedocumentside',
            name='event_situation',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='nfsedocumentside',
            name='facts_version',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='nfsedocumentside',
            name='inss_retained',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='nfsedocumentside',
            name='irrf_retained',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='nfsedocumentside',
            name='iss_retained',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='nfsedocumentside',
            name='issued_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfsedocumentside',
            name='kind',
            field=models.CharField(default='note', max_length=8),
        ),
        migrations.AddField(
            model_name='nfsedocumentside',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='nfsedocumentside',
            name='number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='nfsedocumentside',
            name='replaces_key',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='nfsedocumentside',
            name='retained_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='nfsedocumentside',
            name='service_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='nfsedocumentside',
            name='situation',
            field=models.CharField(default='active', max_length=16),
        ),
        migrations.AddIndex(
            model_name='nfsedocumentside',
            index=models.Index(fields=['organization', 'competence'], name='hub_nfsedoc_organiz_e48326_idx'),
        ),
        migrations.AddIndex(
            model_name='nfsedocumentside',
            index=models.Index(fields=['organization', 'issued_on'], name='hub_nfsedoc_organiz_712e80_idx'),
        ),
        migrations.AddIndex(
            model_name='nfsedocumentside',
            index=models.Index(fields=['organization', 'access_key'], name='hub_nfsedoc_organiz_187b79_idx'),
        ),
        migrations.AddIndex(
            model_name='nfsedocumentside',
            index=models.Index(fields=['organization', 'replaces_key'], name='hub_nfsedoc_organiz_5bcfc1_idx'),
        ),
    ]
